### ISSUE TITLE
[Idea] Evolving Oak Items

### ISSUE THREAD

**Issue by KrushGames** [pokeclicker/pokeclicker#1011]
Add the ability to evolve max level Oak Items for bonuses

Current Behavior
Level 5 is Max

Improved Behavior
Be able to evolve level 5 items for new bonuses, resetting them to level 1, with the opportunity to get to level 10.

Reason for change
Different aspect to using Oak Items + buff to them

Detailed Description
Magic Ball: 5% boost to legendary catch rate
Amulet Coin: 5% boost to dungeon tokens
Poison Barb: 5% boost to base attack
Exp Share: ???
Sprayduck: 5% boost to money and farm coins from berries
Shiny Charm: 5% boost to roamer rate
Blaze Cassette: 5% boost to attack gained from breeding
Cell Battery: 5% reduction in energy regen time

**Comment by KrushGames** [comment]
I did mostly 5% boosts just as a base. If anything feels too OP or too weak, those can be adjusted accordingly

**Comment by liczale** [comment]
https://docs.google.com/document/d/1dRN0Tsu13tw31U05SYs_mcjz04MmVsAO-8V3uQIUi0k/edit?usp=sharing This is my Google doc with prices, boost rates, requirements ETC.

**Comment by KrushGames** [comment]
Maybe we cut those prices in half? i thought the point wads adding a new bonus to the items in addition to getting a higher level cap

**Comment by Ultima1990** [comment]
I'd put the roamer boost on the shiny charm, since they are similar effects, both boosting "special" encounter types.

**Comment by KrushGames** [comment]
cool! i changed that and gave the magic ball a 5% buff to legendary rates to make ultra balls with mb slightly viable compared to masterballs. Also, I will take suggestions and be editing the main comment, so it will show up with your idea.

**Comment by liczale** [comment]
Wait do you guys want me to change it on the doc too or do you have it covered?

**Comment by KrushGames** [comment]
i think it should be covered here, but keep the doc. I really like the idea of mini quests to level them up

**Comment by liczale** [comment]
alright can do.  You guys have permission to edit the doc btw.

**Comment by Ultima1990** [comment]
Here's a pitch I once did for a poison barb upgrade:
Now also puts a (non-stacking) DOT on the target that deals X% of Attack (not click attack) damage over Y time.
The reason to make it a (non-stacking) dot is to make single clicks more powerful (much more powerful) without buffing rapid clicking (AI auto clickers). Clicking again would just refresh the duration. In fact, clicking too fast might even refresh duration before the first tick has a chance to go off. Also, you know, it's poison.

**Comment by sadcubone** [comment]
two suggestions for oak items:

1) when maxed, their effects are applied regardless if they are equipped or not. also equipped ones will have their effect doubled (multiplicative or additive, either one works).
2) when maxed, they gain a global passive which is applied regardless of being equipped or not. (e.g. magic ball active gives %10 more catch rate but the passive gives %5 or less idk)

ideas above mine are great too, i look forward to see them in game. thanks for your efforts.

**Comment by KrushGames** [comment]
so this is gonna take cubone's idea and mix it with a few others. maybe levels 1-5 and then 1-3 stages. So for stage 1, just regular bonuses. then in stage 2, get passive effects for deselected ones and a special effect. stage 3, double the passive effects and the special effects. and the levels are 1-5 for each stage.

**Comment by liczale** [comment]
Krush I believe that to be a good solution.  The issue then being is what kind of special effects do you have in mind for them.

**Comment by RedSparr0w** [comment]
> 1. when maxed, their effects are applied regardless if they are equipped or not. also equipped ones will have their effect doubled (multiplicative or additive, either one works).
> 2. when maxed, they gain a global passive which is applied regardless of being equipped or not. (e.g. magic ball active gives %10 more catch rate but the passive gives %5 or less idk)

Those are way too OP, basically defeats the purpose of having a limit on how many can be active at once.
Not everything needs to be boosted all the time..

**Comment by liczale** [comment]
How about when the evolved item is maxed they get a global passive equal to 10% of what having a max evolved equipped would be.  Like having a max Evolved Magic ball would give 15% catch bonus, and the global passive would be a 1.5% extra catchrate.  Does that sound like an acceptable comprimise?

**Comment by RedSparr0w** [comment]
I'm definitely opposed to the idea,
There's no real reason to apply more bonuses.

**Comment by liczale** [comment]
Okay then how about we just keep it to what it was on the google doc linked above?

**Comment by unclebanks** [comment]
If I may add something, I think that even if the suggested changes are OP that SOMETHING should be done with the oak items. It is somewhat pointless to place emphasis on items in both space on the screen and in the coding for them to be maxed out in kanto without further improvement.

**Comment by liczale** [comment]
Banks if you can think of a balanced thing to do with them suggest it because our ideas are coming to no definitive answer.

**Comment by unclebanks** [comment]
To be honest I don't. I'm not familiar enough with the inner workings to even give an educated guess but I'm happy to try. Possibly unlock additional tiers for regions unlocked. That might mitigate some of the headache with going to a new region. Especially since the millions and above are right around the corner. And if not make any changes at least remove the view of it and replace it with berry farm since it's continuously being worked on. I'm just not sure so much screen area should be given to a function that is pretty much idle when there are a lot of developments in other sections.

**Comment by liczale** [comment]
I agree with your statement, and my suggested changes were put on a google doc linked somewhere in the above chain on this PR.  The issue is no one suggests what kind of boosts or prices other than myself so I feel like everyone else is saying. X is bad and leaving it at that without giving any substantial feedback on why other than "It's too strong".  I want someone, in this case you specifically, to just write your ideas for what you want them to look like on the docs, as its openly available for everyone to edit, and see.  I have a feeling the more peoples ideas we have for what they do, their unlock conditions, etc.  Will make the ending decision of what we are going to do with these "Evolved Oak Items" significantly quicker than if everyone just continuous to ignore the problem that they create with uncreative criticisms.  Additionally since no code has been worked on here any, and all suggestions are still a possibility at this stage as we have no reason to stop suggesting as there will be no issues cause by random choices, or redoing the whole idea from scratch.  Lastly I want to address the issue of cost / unlock conditions.  Once again no one except myself has said anything that is even remotely close to a challenge to balance out the fact that these would be late game buffs to help people get through the Sinnoh to Galar area as the mathematical challenge they propose needs to have some sort of buff otherwise the game will be breed, and grow buff, instead of being the fun Pokeclicker that was originally intended.

**Comment by unclebanks** [comment]
I agree with you completely but at this rate it will never be completed. The best way is to throw something out there and see what works. That should've been the purpose of the dev branch. Maybe make another dev branch to test offshoot ideas and keep this one for R.C. testing. The best way to move forward, in my opinion, is agree on the unlock conditions and begin throwing numbers and testing. With as many variables that are present it is going to be difficult to try and work out what is the best solution without narrowing the options.

**Comment by RedSparr0w** [comment]
> If I may add something, I think that even if the suggested changes are OP that SOMETHING should be done with the oak items. It is somewhat pointless to place emphasis on items in both space on the screen and in the coding for them to be maxed out in Kanto without further improvement.

Not every mechanic needs to be able to be modifiable after Kanto.

Maybe the problem isn't that the Oak Items need to be boosted, maybe they are just way too easy to max out..
They were initially made when only Kanto was a thing.

Everything seems to just be getting boosted, and I personally don't think we need to make the game any easier on the front of oak items.

There's already a passive boost for EXP and Money from achievements, extra boost from Battle Items which can be all be activated together, and with Oak Items to further boost the Oak Items effects.

It's not the worst thing to need to have something activated for it to help you in the game, and not help you out if you don't have it activated.
If you are focusing on money, have that item active, if not, don't..

**Comment by unclebanks** [comment]
Yes but oak items boost other things that there are no items for such as catch rate, shiny rate, berry speed, and hatching speed. There are currently no other ways to boost them. I don't even want to mention click attack which only amounts to 26k~ when maxed. Click definitely need a buff or they are going to be irrelevant with unova+

**Comment by RedSparr0w** [comment]
> Yes but oak items boost other things that there are no items for such as catch rate, shiny rate, berry speed, and hatching speed. There are currently no other ways to boost them. I don't even want to mention click attack which only amounts to 26k~ when maxed. Click definitely need a buff or they are going to be irrelevant with unova+


Catch rate doesn't really need more of a boost IMO.
_(other Pokeballs will also help with it a little in the future)_
Shiny rate is already pretty decent too IMO, any higher and they will be too common.
Berry speed does have other ways of boosting now with the Farm overhaul implemented.
Hatch speed is already super fast in future regions with the amount of steps each defeat gives.

**Comment by unclebanks** [comment]
Yepp, everything you said defeats my comment. I wasn't aware of the updates concerning the balls or berries. Realistically it seems like everything else has been upgraded so maybe the question should be should the oak items be removed and reworked into the existing upgrades that are coming?

**Comment by RedSparr0w** [comment]
I don't think there is any point in removing them either tbh, as the other upgrades don't necessarily help in the same way.
Also there is 2 other oak items that were added along with the Farm overhaul.

The other bonuses are all mostly time gated as well, where as the Oak Items are permanent, though selective.

**Comment by liczale** [comment]
Going off of Reds Points:
Better Idea, we make them an alternative form of the Oak item, you get the normal 3 slots, and 1 of the normal slots can be the Evolved Oak Item slots too, so that way we can make them fairly powerful but still keep some balance.  I also would like to see the integration of new oak items, but as I have been watching a lot of Hades.  I feel like stealing their idea of 2 type items might be neat too.  

My Evolved Oak Ideas:
Thus I'm thinking that Evolved Magic Ball would instead of boosting catch rate, would boost DT, and lose its normal Effects.  Amulet Coin would make Quests give more Tokens.
Poison Barb would increase your AFK attack or Attack Speed.
EXP share would Give more Shards from battling (assuming the flute idea or something similar takes place later).
Sprayduck would Slow the growth of berries meaning that they last longer before dying but makes it unable to mutate.
The Shiny Charm would make route shinies higher by an amount and not affect eggs at all
Blaze Cassette would decrease the speed of eggs hatching, but increase the shiny chance.
Cell Battery would give a chance to get double underground drops, but slow energy recharge rate
Squirtbottle would drastically decrease the ripened lifetime of a berry but drastically increase its mutation rate (like dying 10 times faster and getting a 3-4 times multiplier to its mutations would be nice for some of the later berries that are just mutation waiting the game)
Sprinklotad would Decrease amount of berries dropped to where you get only the original planted, but would make replants a guaranteed thing when maxed out.

Other:
Then again we don't need all of them to be able to evolve.  So we could easily scrap some of these and only have a few select oak Items actually have evolutions for now, and we could save the rest for when other overhauls/regions come out.  Hope I can get feedback on this, and see how you think of these Upside/Downside things, just changing their affects to be slightly different, or just be wacky yet related to the original,.

**Comment by KrushGames** [comment]
liczale i feel like you just said to nerf half the items. cassette, cell battery, and all farm items seem to be getting nerfed. Maybe just neutral on their original effect and not a nerf there?

**Comment by liczale** [comment]
Well they're not nerfed, they have their original forms too, the issue is these are pretty powerful as they are normally so I am trying to think of things that aren't there or need to be more powerful still.  But the cassette would infact be practically useless so yeah that one was pretty bad.  The cell battery would be really useful as you don't need to have it equipped all the time until you unveil the items, counteracting its downside if you're so inclined to care about it, plus don't we all just use potions anyway?  And yeah I had no Idea what to do about the farm items because they really can't be slightly altered without making them either way too OP or too weak so I just used threw out idea, albeit bad ones to fill those slots.  but as I stated in other we only need to have a few of these first, as we can work on the others later in other regions/overhauls.

**Comment by KrushGames** [comment]
I feel like starting out by hitting a few is good, as we can gauge reactions to those changes. The idea to keep 2 regular slots and an evolved slot is good. Maybe for the evolved ones though, we can keep the old bonus and add half that of the new bonus. Magic ball seems to be pretty balanced and agreed upon at a 5% catch rate bonus so adding a 2.5% dt gain to that seems like a good place to start off.

**Comment by liczale** [comment]
Alright sounds great, only issue is I have no Idea how to make that, but yeah I think community feedback will definitely be helpful with this change, and having them be their default and evolved would definitely make some of the items that are less useful in late game more relevant again.  I am under the impression we will still have the evolved items be a five stage thing unless you think we should have the evolved level be the same as normal, though I think having them have an Evo level unlock at max normal level would make more sense, but I'm open to anything.

**Comment by liczale** [comment]
Aight so I've put some more thought into this and have decided on a few that I think would be fair, and some rules they would work upon.  I think that having the Evolve versions also have level ups would be nice, but instead of doing things X amount of time perhaps we could make them things like Quests.  Additionally I still think the 3 slots is good if perhaps the new slots for evolved come around when you become champion of X region.  My current though being Galar (8), Unova (5), and Kanto (1).  This just being so Unova has an extra special feature to go with its eventual release.  The normal oak item effects would still be active but they would also have their secondary Evolved form effects too, and the leveling would be 6 for first level Evolved to 10 for max level evolved.

Items and their Challenges:
Evolved Magic Ball would boost DT by 10% per level, making it max out at a 1.5x multiplier for DT.  The Challenges would be to catch X amount of Pokémon in a row.
Amulet Coin would make Quests give more Tokens, and Quest XP by 10% per level.  The Challenges would be to finish X amount of tasks in a single day making it something you'd have to go out of your way to do.
Poison Barb would increase your AFK attack or Attack Speed.  No Idea for the Challenge but I'm thinking along the lines of defeat level X in the Battle Frontier.
EXP share would Give more Shards from battling (assuming the flute idea or something similar takes place later).  With the Challenge being to leave whatever that idea is on for X amount of time.
Lastly Sprayduck would Slow the growth of berries meaning that they last longer before dying.  The Challenge being something along the line of Harvesting X amount of berries overall or in a certain amount of time.

I have no Idea how to program this but I just want feedback on these, cause I'd really like to have these implemented before the release of Unova

**Comment by liczale** [comment]
Just waiting on Red's Feedback on this

**Comment by KrushGames** [comment]
i feel like this gained a lot of support/ideas, and then died out for 2 months

anyways, im reviving it, so please comment any ideas/approval/willingness to help with coding

**Comment by silasary** [comment]
I'm happy to do the code stuff, but there were a lot of ideas thrown around, and I'm not sure which ones we actually want to do

**Comment by Farboo171** [comment]
Stale issue, associated doc with more details has been deleted. Closing, open a new suggestion with the specifics if you are still interested in this idea.
