### ISSUE TITLE
[SUGGESTION] Make league one-shot battle like original games. 

### ISSUE THREAD

**Issue by Claygame** [pokeclicker/pokeclicker#1038]
the one thing i find odd is that everyone is trying to bring this game into just how the original games are but no one thinks of making the League battles the way it is ingame - a non stop 5 battles in a row.
maybe we should have that here too with clock giving you 2 minutes to defeat all 5 trainers in a single go.
one big benefit of it will be that people have to really look at their dps to make any progress into the next region, making their life easier in next region while not having to breed without a clear goal for damage they might need.
Additionally, Elites will become less of a target for shard farming (maybe its not an issue that needs resolving but the change will do it anyway) 

Now this will also mean we need changes in achievements as well since there wont be defeating a single trainer 1000 times. it can be changed to defeat league time 10/100/1000/2500/5000 with % bonus from current bonuses added and properly divided.

**Comment by antocs** [comment]
Since the plan is to make the League the more similar to the main games, regional/national dex feature too, meaning that the DPS for the League will only be calculated from the pokemons of that said region, since the national dex is received after beating the champion (so the regional dps will only be for the first League run?).

**Comment by jk13pclick** [comment]
Closing, we have decided that this issue does not fit with our current vision for the game.
