### ISSUE TITLE
[SUGGESTION] TMs & Rematching Gyms

### ISSUE THREAD

**Issue by Awec4** [pokeclicker/pokeclicker#1146]
**Current Behavior**
TMs are a fundamental part of Pokemon, usually offering the player more powerful moves in each type. Pokeclicker currently has no concept of TMs and it doesn't seem that anyone has suggested anything for them.
In addition, rematching Gyms isn't very interesting currently which makes the achievements more a test of patience than anything else.

**Improved Behavior**
My suggestion for TMs is a simple system which buffs the damage output for the TM's type by some amount for some period of time (exact values will need balancing). This may not sound very interesting, but I think it could work well with my second proposal, which is that rematching Gym Leaders starts an endless battle where each rematch becomes more difficult, similar to the Battle Frontier. The Gym Leader could also gain additional team members, similar to how they do in the games where you can rematch them. At the end of the battle, the player is granted a TM of the Gym Leader's type with power depending on how many consecutive rematches they achieved, or alternatively multiple TMs with the amount depending on consecutive rematches.
TMs could also be found randomly from a pool in Dungeons.

**Reason for change**
I think this could make rematching Gym Leaders much more interesting, and would also make collecting items in Dungeons more worthwhile. I also think that this is a reasonable representation for TMs, given that Pokeclicker doesn't have a moves system.

**Comment by locodude0001** [comment]
I agree that we need TMs but I have a different vision for how it would work.

I think TMs should add an attacking type to a Pokemon. Only one at a time. You can overwrite the type with another TM. The added type would include a small icon near the Pokemon of that element rather than displaying it as a triple typing.

As the game stands right now, I think it'd be neat to include them as Battle Frontier shop rewards or creating a new facility in Sinnoh's Fight Area. The TMs don't have to be labelled as every attack, I think it'd be okay to just label them as TM [element] (EX: TM Electric, TM Rock). This way you only need to create 18 more items than hundreds.

You can go through an entire list of moves every Pokemon can learn and blacklist certain elements if they can't learn it, but I think it'd be okay to just let any Pokemon learn any element.

Additionally this may also require a new NPC for the Move Deleter. He'd just remove a Pokemon's TM type, maybe for a fee and maybe not.
