### ISSUE TITLE
[SUGGESTION] Move Scripts to Modules

### ISSUE THREAD

**Issue by unclebanks** [pokeclicker/pokeclicker#1175]
**Current Behavior**
Code is currently split between modules and scripts

**Improved Behavior**
Move Scripts to Modiles

**Reason for change**

Simplify the code
**Detailed Description**

I am looking for a dev(s) to help me with moving the script to modules. This is an overwhelming amount of work so I suggest getting multiple people involved and splitting the work to have this process finalized prior to the new regions being added and possibly making the process longer and/or more difficult.
**Screenshots:**

**Comment by anapple96** [comment]
First of all, modules won't simplify the code, at all, they will make it more complicate actually. The actual reason why we (well, technically Spenser started it and we followed) is because :
- Full type checking throughout the code base
- Ability to bundle the code in a cleaner way (at least Spenser promised us it would be cleaner than the current Gulp setup)
- Improved compilation and reloading in development (also currently limited due to supporting old and new)
- Remove circular dependencies and condition races
- (Maybe) Cleaner code (Clean =/= Simple)
(Read this for more detail : <https://github.com/pokeclicker/pokeclicker/pull/871>)
Next : You should really create a checklist for this, as you'll never finish if you port all at once. Port incrementally, and create a checklist to keep track of it.

**Comment by unclebanks** [comment]
Completely was not the answer i was hoping for. Might be the answer i needed, but not what i was hoping for.
