### ISSUE TITLE
[SUGGESTION] EVs

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#1225]
In the main games each pokémon gives 1, 2 or 3 Effort Points to a stat upon defeat. 4 Effort Points in a stat gives 1 Effort Value, which is basically +1 to that stat. Every Pokémon can obtain a maximum of 510 Effort Points.

So how to translate this to clicker? First off, forget about defeats. Captures is where it's at. People have wanted a reason to catch dupes, so here it is. Second, forget about stats, think about Pokémon. Catching a Rattata will give 1 Rattata Effort Point. You want to buff your Rattata? Go catch lots of Rattata! What would Effort Points do? I'm not sure about the numbers, but for the sake of example, let's say 10 Effort Points give 1 Effort Value. What is Effort Value gonna be? Here it comes, the dreaded _multiplier_.

Here's what I'm thinking. Start with an EV multiplier of x1. Which means it changes nothing. Every Effort Value adds +0.01 to that multiplier. That's the simple part, because this will only work up to x1.5. After that [insert magical formula that gives ever decreasing returns that will forever approach but never quite get to x2 here]. Basically, diminishing returns. Every catch will contribute _something_ until we stop counting decimals, the value of an Effort Value will decrease constantly, and the multiplier will get ever closer but never quite get to x2. Once upon a time I knew how to make such a formula, but for some reason I'm drawing a complete blank. This, right here, is my attempt as using a multiplier without letting it scale way out of hand. The result should be a system that complements breeding, doesn't make breeding useless, isn't made useless by breeding, and can theoretically be done forever just like breeding.

What about Pokémon that can't be caught anywhere? Will catching Rattata also give Effort Points to my Raticate? No. There's many Pokémon that don't have a wild or dungeon location because they are evolutions, can only be hatched or purchased, are at the end of a dungeon with a large boss pool, etc. To help with this, Effort Points will also be obtained by hatching, at a rate of 1 per hatch. Yes this means some Pokémon will be way harder to EV train than others. So be it.

EV training should not be available from the start, and it should not become available at the same time as breeding. I've always thought that systems like this should be spread out, giving players a new system to play with every once in a while as they progress through the regions. I'm currently eyeing Sinnoh for this one, as it has no real unique systems right now. So how to gate EV training. Potentially inspired by current events: PKRS. PKRS or Pokérus is a main game virus that doubles a pokémon's EV gain. In clicker only Pokémon that have Pokérus can gain EVs at all. At some point in Sinnoh, as part of progression or from a shop or whatever, one random Pokémon in your list will get it. Yes, you'd pay to have one of your Pokémon intentionally infected with a contagious virus. Don't worry, there are no negative effects. Players can then spread it through the hatchery. Only Pokémon in the _hatchery_ will spread it, _not_ in the queue, spreading to 31 Pokémon at a time is a bit too fast, it becomes too easy to infect your entire roster. The spreader will only be contagious as long as their hatching progress has not reached 100%, otherwise you can just leave one Pokémon in the hatchery forever until everyone is infected, again, too easy. Pokémon that have freshly contracted it will not be contagious unless they have hatched at least once, otherwise it'll just be an easy casual chain reaction. The goal is to get people to think a bit differently about who they put in there, at least for a while until the entire roster has it.

That's it. EVs for clicker. Share your thoughts.

**Comment by Ultima1990** [comment]
Before someone points it out, yeah, it'd take quite a bit of active breeding. _Active_ breeding. To spread PRKS. I'd like to alleviate that a tiny bit by adding this: There should probably be a PKRS based sorting method for the hatchery. The goal is to get people to think differently about what to put in there instead of just blindly queueing up the most efficient breeders. At least for a while. Part of that is _not_ to make it frustrating to find one spreader and several receivers in a ~700 (soon more) pokémon long list. Some convenience there would not be bad.

**Comment by KrushGames** [comment]
would pokemon that are not regularly bred be liable to lose it, or would it be a permanent status?

**Comment by Ultima1990** [comment]
PKRS would be permanent, the ability to spread it would also be permanent (unlike in the main games).

**Comment by Heppity** [comment]
> 

Honestly this seems really weird to add EVs like that as one of the issues I see is what would this contribute or add to pokeclicker experience rather than just a another multiplier source while it encourages catching pokemon, that 5000 pokecatch for one pokemon isn't gonna attract people to waste grinding in earlier and just grind on the one they can One Hit KO instead for maxmium DTs

**Comment by Ultima1990** [comment]
It contributes a way to gain power that isn't just breeding. Because that is what this game mostly is right now. Breeding simulator. This adds some variety. In addition people have expressed that they want catching duplicates to be worth something other than DT, so two birds one stone.

**Comment by Claygame** [comment]
if kept as current idea, maybe gaining of points can be same for all poke via hatchery instead of only non-route poke but can also be gained by catching on route. catching in dungeons should probably give extra than route catching since more effort needed.

but, 
overall idea seems ok but in the end it still keeps this game as breeding stimulator. People will rather breed to get the boost instead of catching on weak routes and wasting time so those legendary pokes will just get fatter. The only thing that will deviate people from just focusing on poke that can earn it by hatchery is to make it route/dungeons exclusive. another way would be that doing battle-frontier will give 1 point for whatever poke u defeat in it, making BF a bit more useful as it will turn into an only easy source for non-route exclusive poke's points and people will not mind that the run is taking over an hour. can use the shard gain formula in bf for it too if 1 point seems too low for floor lvls such as 500+

**Comment by Ultima1990** [comment]
> if kept as current idea, maybe gaining of points can be same for all poke via hatchery instead of only non-route poke but can also be gained by catching on route. catching in dungeons should probably give extra than route catching since more effort needed.

Reading hard?
