### ISSUE TITLE
[BUG] when i make loadout for oak items if i switch to 2 from 1 the items are reset on 1

### ISSUE THREAD

**Issue by pokeclickerboi** [pokeclicker/pokeclicker#1289]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by pokeclkermaniac** [comment]
Double-check that you are setting your Loadouts correctly. I made the mistake of clicking a loadout number (i.e. 1) then clicking the Yellow area to select items, then switching and it wouldn't "save".

In the List, at the top you have to switch from "Selector" to "Loadouts" in order to actually set your loadouts.

**Comment by RedSparr0w** [comment]
Closing as no new info, seems to be sorted?
