### ISSUE TITLE
[SUGGESTION] Add filter to protein usage menu

### ISSUE THREAD

**Issue by karankhosla** [pokeclicker/pokeclicker#1300]
**Current Behavior**
The game currently only has a sort dropdown. 

**Improved Behavior**
Ideally the protein usage menu would have both the sort and filter functionalities, similar to the hatchery. 

**Reason for change**
This will make it much easier to apply proteins to much more specific groups of pokemon - e.g. non-shinies of the newest region. 

**Detailed Description**
Expand the protein usage menu to have both a sort and a filter functionality. They could be minimizable, like in the hatchery menu. The filter menu could also be a pop-out, which would be inconsistent with the hatchery, but still okay. 

**Screenshots:**

**Comment by KingisNitro** [comment]
I strongly support this. Using Proteins shouldn't be this hard. I want to filter out specifically the region I'm in, but cannot, so I have to do it in hatchery/list, make a list, and then go to the Protein menu. It's somewhat annoying.

Ideally also, Hatchery list has sort by "Proteins Used" option, but does not have a "Proteins Used" Display Value. So I can sort them, but I won't know how many were used. This should also be added and would make it easier to know which of them need or don't need any more Proteins.
![obrázok](https://user-images.githubusercontent.com/25939167/112724491-fd321300-8f13-11eb-86b9-ff9d449084b3.png)
![obrázok](https://user-images.githubusercontent.com/25939167/112724473-dd9aea80-8f13-11eb-94bb-ea186e8502b9.png)

**Comment by IanWalder** [comment]
To be fair, this entire point is moot if your endgoal is to protein every Pokemon you have to the maximum amount, and there's not really any reason why it wouldn't be.

**Comment by KingisNitro** [comment]
> To be fair, this entire point is moot if your endgoal is to protein every Pokemon you have to the maximum amount, and there's not really any reason why it wouldn't be.

That is simply incorrect; yes, I want to Protein all Pokemon to the maximum, but that costs a lot of money, that I might not currently have. Thus I want to pick the most efficient strategy at the moment, which is to use Protein on a Pokemon that
- has the highest Breeding Efficiency
- Is from the region I am currently in.

When I am in Hoenn, I do not want to use Protein on a Kantonian Pokemon. I want to pick the most efficient Hoennian Pokemon, because they have the highest power in Hoenn (this is more pronounced in other regions, where they have less %). I would also specifically breed Hoennian Pokemon, because their power boost is the highest when compared to the previous regions. Hence by that sorting even exists.

So, no, this is absolutely not a moot point. This is about efficient usage.

**Comment by Pyrii** [comment]
I wanted to filter by favourites, I think a simple stopgap measure would be to add favourite markers to the list for now so I can quickly see which are my favs.
