### ISSUE TITLE
[SUGGESTION] Automated Dungeons

### ISSUE THREAD

**Issue by liczale** [pokeclicker/pokeclicker#1315]
**Current Behavior**

Nothing

**Improved Behavior**

I would like to see a button that after beating any given region unlocks the ability to automated doing a specific dungeon

**Reason for change**

You all have a 1000 times dungeon achievement and that is hellish, and overly time consuming.  This would solve that problem and wouldn't be terribly hard to do.

**Detailed Description**

I propose that you have an (Auto Run) feature for the dungeon, where it goes around the outside of the area, then upon completing that outer ring it goes inward 1 more, and it will proceed to do this until it finds a chest or the boss, where it will automatically collect the chest or engage the boss.

**Screenshots:**

![Dungeon Edited](https://user-images.githubusercontent.com/72051633/111188661-47fe7300-8583-11eb-88ee-0205e807925e.PNG)

**Comment by Ultima1990** [comment]
I've been thinking of a way to possibly do some kind of dungeon automation.
It'd involve an upgradable system. By default it would just randomly go directions, moving one tile every X [time] in a random direction, fighting enemies, ignoring chests, probably often failing and eating into your DT. Then upgrades come in which would be purchasable in various shops for various currencies. These would include:

Increasing the speed at which it moves tiles (possibly multiple upgrades and/or an oak item).
Allowing it to "teleport" (moving to any tile a player could go to by clicking).
Making it so it doesn't revisit tiles it already visited (if purchased before the teleport upgrade this one allows it to teleport in situations where it would get itself stuck with its random movement, like situations where it drives itself into a corner or otherwise surrounds itself with revealed tiles that it's not allowed to enter because of this upgrade).
Enabling a toggle that allows it to open chests (maybe you sometimes don't want it increasing the boss' HP).
Allowing it to do click damage.
Increasing the speed at which it does click damage.
Making it actively seek out chests when they are revealed (maybe toggle?).
Making it actively seek out the boss when it is revealed (maybe toggle?).
Enabling a toggle that allows it to use battle items.
Giving the player an option to pre-program a route.

I'm thinking possibly also a penalty to attack, which would again be reduced by upgrades.

The point is that without many of these upgrades it might get lucky and succeed, but will often fail, making this automation significantly less efficient than running dungeons manually. The upgrades would increase that efficiency but require time/currency investment and even with all upgrades running manually *should* still be more efficient.

**Comment by liczale** [comment]
Ultima I like that a lot, but I have some tweaks of my own I'd like to suggest to your list.

The increase in speed should have a regional cap because of the size of dungeons, No Idea what the cap would mathematically but it should be just slow enough to miss one column/row worth of tiles, making it so there will be no point at which it is fully efficient.
The Teleport ability sounds cool and all but it sounds impractical unless that AI knows what its doing because otherwise it could just warp around and be a massive detriment to itself unless you already tell it not to revisit its old tiles.
The Revisiting of Tiles is also a great idea but it has the opposite issue of teleportation where it could softlock itself without the ability to teleport being unlocked, so I think linking them as a single ability would solve the entire issue.
The Chest toggle sounds great but a toggle for opening the chests as a boost for sight would also be great, and by that I mean pick up 2 chests to show the other map chests, 4 chests to show all enemies and the boss, or no chests where it goes in blindly would be a massive boost to it, and thus we could make it cost a small fortune as these would greatly boost the AI's speed in clearing dungeons.
The Click damage is actually just a fantastic idea and I can't find anything to suggest upon.
The Boss seeking reveal should be something that is a base unlock as its otherwise just a way to not click the screen or use the arrow keys and without this it is pretty useless.
The Chest toggle I would combine with the toggle of chest collections just for ease of use.
Battle items should be dealt with by the player otherwise it would give the dungeon AI the ability to be significantly better than doing it in person (that 50% boost should be meant for active people or those among us with billions of PokeCoins to spend on 99+ Hrs of it)
Pre-Programmed Route should be unreasonably pricy that is if the AI is as dumb as a rock because this could be incredibly powerful with the larger dungeons, assuming the AI moves randomly.
The Attack Penalty should cut the attack in roughly a third or half as the base so it can't be used for Dungeons that are at your current level, and can only be used in the past dungeons where you'd be farming them for a specific Pokémon.

Does this sound like where you were coming from, and by that I mean as a reasonable understanding of what you intended?

**Comment by Ultima1990** [comment]
I'm thinking the teleport upgrade + no revisiting upgrade might just be OP as all hell. Possibly scrap the teleporting upgrade but still allow it to teleport if it gets stuck with the no revisiting upgrade.

**Comment by liczale** [comment]
We could make it a consumable item, I.E. the escape rope if we want it.
Or we could just leave it as its "Emergency Escape" function and just leave it as free.

**Comment by anapple96** [comment]
Don't think this is longer relevant with the current plans we have

**Comment by coeusite** [comment]
Hi, I made a javascript for dungeon automation. You may try this https://github.com/coeusite/PokeClicker-Helpers

**Comment by jk13pclick** [comment]
Closing, as not planned for the game in current state.
