### ISSUE TITLE
[SUGGESTION] Shiny Trainer/Gym Pokemon

### ISSUE THREAD

**Issue by scolpitts536** [pokeclicker/pokeclicker#1317]
**Current Behavior**
The pokemon show up with no noise or notification

**Improved Behavior**
Maybe just a noise to let us know we got a trainer/gym shiny

**Reason for change**
Its a shiny and with no noise even if it is frustrating to get one its still a shiny

**Detailed Description**
Same shiny noise goes off like all the rest and if a notifcation also then it should be like Example: Bug Catcher Doug's Weedle was Shiny!

**Comment by Qwertypop4** [comment]
The only purpose of these is to make leveling the Shiny Charm easier (and possibly because it's easier than having it not happen), but this would just be annoying, unless there would be added a shiny "seen" dex, which this would tell you something has been added to. Otherwise, I see no good reason for it

**Comment by jk13pclick** [comment]
Closing as not planned for the game.
