### ISSUE TITLE
[SUGGESTION] Rare candy as breeding skip

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1407]
**Current Behavior**
rare candy has no use

**Improved Behavior**
The rare candy could be used to give an pokemon +25% attackbonus from base attack (1x breeding)

**Reason for change**
Gives rare candy a use without being overpowered. Just saves some time and buffs Legendary by doing so.

**Detailed Description**
The usage is very simple. It skips 1x breeding and gives you the bonus instantly.
It's pretty wothless if you only have one and if your Pokemon didn't have any proteins so far.
But if you use them wisely they could give you an huge instant boost in terms of saving time.

The rare Candy could go with the price of masterballs so you can't just buy a bunch and power up any pokemon.
You can buy it but it should not be worth to do that in general (except you have too much money).

Instead reward it for milestones. Like finishing a region, getting the highest stage of an Achievement, High Stagelevel reward for battle frontier and/or other stuff like that. 

The best usage would be on high base attack but low breeding effency pokemon - also known as most of the legendarys. So it would buff these Pokemon too.

**Comment by GarrikFel** [comment]
If this were implemented, it would have to be less than 1 billion per rare candy.  Let's say you use this on a legendary.  How much time are you saving?  If you're idling, you're not saving any time, and if you're actively clicking in your highest 1HKO spot, you're saving about a minute (just tested it for a couple of legendaries).  1 billion per 1 minute saved isn't good.  100 million is better, but 10 million is probably the sweet spot.  You can get a couple million from trainer battles in certain dungeons, so 1 minute spent in a dungeon results in saving a minute breeding a legendary.  It would allow you to keep a certain favorite as the most powerful member of your team.

**Comment by NiCeDiCe90** [comment]
10 million? You underestimate the amount of money people have massively . They could just buy them in 1k stacks. 
Imgaine getting 1000 instant breedings on a high base attack Pokemon. Pretty op.
100 Million might be ok idk.
This would need some testing on how much impact one super boosted Pokemon really can have.

**Comment by Ultima1990** [comment]
How about this for balancing. Every time you use a candy on the same pokémon, it needs twice as much candy for the same effect.

**Comment by GarrikFel** [comment]
I think of it like this, if you have billions of coins, then your pokemon attack should already be ridiculously high.  After all, that much money requires a lot of game time, and if you're breeding that whole time, your attack would be ridiculous.  If you're not breeding during that time, now you didn't waste all that time, and can retroactively breed.  

At that point, does breeding even mean anything anymore?  You would probably need 1k hatches in order to make any kind of noticeable difference in your attack.  While 100 million would be ok, it seems really pricey to save a minute of your life.

Ultima, I guess it depends on how much money Alola and Galar will give out.  If we double the requirement, we might want the price to be even lower than 10 million.  Coding wise, this might be fairy tricky when you start needing 1k candies to get the equivalent of 1 hatch.

**Comment by Penguindude2000** [comment]
i mean i get what, 13m a night from offline progress on one of the early johto routes, with not too much ach %, so id imagine youd get significantly more with last route oneshot, the money item, amulet coin, and max %.

**Comment by GarrikFel** [comment]
I have about an achievement bonus of about 590%.  My max one shot idle route is (I'm going to round up) 23,000 in Kalos.  So, 23,000 * 60 seconds * 60 Minutes * 8 hours = 662.4 million.  Getting 1 rare candy overnight at low%, and 66 at high % seems about right to me.  I would need 66 to even notice a change at this point.  If rare candies cost 100 million, and all they do is give me one effective hatch, only getting 6 overnight is not worth the effort to click through the menu to use it (Or rather, it FEELs not worth it, it would still be worth it).  If rare candies cost 1 billion, then I'd rather save my money in case some other better money sink gets introduced into the game.  That's just me, and I'm willing to admit to being "frugal" (AKA cheap) with my fake currencies.

**Comment by Farboo171** [comment]
Approved, as unpurchaseable but found as rare loot some places like the Safari Zone or as BF milestones and quest rewards

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
If I may. I don't know if skip breeding was interesting 2 years ago but it doesn't seems really attractive now especially if the drop rate is low. Also it feels like only the strongest Pokemon would benefit it.
I would like to suggest an alternative :

**Current Behavior**
Rare candy has no use.

**Improved Behavior**
Rare candy converts the Pokemon "Hatched" into "EV".

**Reason for change**
Gives rare candy a use.

**Detailed Description**
On using a Rare candy onto a Pokemon, it reset the "Hatched" statistic to 0, reset the attack of the Pokemon to Base Attack and add the "Hatched" statistic into EV.

For example, if my Pidgeot has been hatched 3000 time and has 50 EV, using a rare candy would bring it to 0 hatched time, 3050 EV and an Attack of 112.

**Comment by DraKay** [comment]
That's totally unbalanced... Already seem mad with your low hatch number in your example. Think that some people have already 10k hatches or more in their pokes

**Comment by LuchoDreamer** [comment]
Could you do this over and over? I guess so, to not create FOMO.

` it doesn't seems really attractive now especially if the drop rate is low.` 
Even though I agree with you on this, it's what we want to do with Rare Candies. But honestly your idea sounds interesting. Maybe not balanced exactly in the way you described it, but it's like a prestige mechanic from other incremental games, that maybe we could insert into the game in the future in another way with a different balance.

**Comment by RegisCoaxans** [comment]
We want the Rare Candy to give a little boost. We expect it to be helpful, not useful. We do not want people to look for them as a main reward in various places so it is fine not being very attractive.

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
`That's totally unbalanced... Already seem mad with your low hatch number in your example. Think that some people have already 10k hatches or more in their pokes`. Is it the resetting of the attack or the free EV that is unbablanced ?

I guess it could be unbalanced for Pokemon that cannot gain EV but I thought the friend Safari would give EV to any Pokemon. Also since the EV as a really slow progression I wonder if it was a big deal. I'm not real aware how many EV ppl have gathered so far.

`Could you do this over and over? I guess so, to not create FOMO.` 
I don't know what FOMO is. Yes, could be done several times. I thought also that adding a sort of "new game +" would fit the game.

`We want the Rare Candy to give a little boost. We expect it to be helpful, not useful. We do not want people to look for them as a main reward in various places so it is fine not being very attractive.`

What kind of small boost is expected ? The way you describe the item make feel that it's gonna be a bit useless. ^^'

**Comment by Farboo171** [comment]
The "small boost" is to be one breed, so +25% of base attack.

Its not supposed to be a gameplay-shifting breeding replacement, it is supposed to be a neat little reward for doing stuff that you can either use right away or stockpile for when you get that legendary you REALLY don't want to breed to get to Mega attack requirements, or whatever.

They won't be especially exciting for players with millions of attack, but newer players will find them useful.

**Comment by xslk** [comment]
EV mechanic was instill to reward people for catching more of the same pokemon. Giving rare candies to a pokemon to convert hatches to EVs completely goes against this reasoning. EVs give diminishing returns, but if I were to use it on this
![image](https://github.com/pokeclicker/pokeclicker/assets/100386196/f8b64610-fb9b-484f-9d9c-a481e4276dfe)
That's a huge jump in EVs.

This would also kind of make other vitamins useless since feeding pokemon carbos to pokemon to hatch faster would be easier then inputting what is the current optimal vitamin spread and then feeding it a rare candy after.

Another thing to consider is the pokemon statistics model, will number of hatches change in the statistics model, or will an new line be added with lifetime hatched, hatched since last rare candy and rare candies used. If you stick with the current pokemon statistics model and just reset hatched to 0, does this also completely reset the pokemons attack to base*EV bonus or will the attack remain with all accrued bonuses but with hatched being 0?

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
`They won't be especially exciting for players with millions of attack, but newer players will find them useful.`
`EV mechanic was instill to reward people for catching more of the same pokemon. Giving rare candies to a pokemon to convert hatches to EVs completely goes against this reasoning.`

I see. Indeed adding such change to the rare candy wouldn't make sense. Plus, I didn't really thought about the carbos that would outweight the others vitamins.

`If you stick with the current pokemon statistics model and just reset hatched to 0, does this also completely reset the pokemons attack to base*EV bonus or will the attack remain with all accrued bonuses but with hatched being 0?`

Yeah the idea was to reset attack to base * EV bonus.
