### ISSUE TITLE
[SUGGESTION] Improving dungeon while waiting rework

### ISSUE THREAD

**Issue by raven0ak** [pokeclicker/pokeclicker#1411]
**Current Behavior**
As region increases, dungeon size becomes larger, but 1 minute timer to clear stays generating somewhat high tier annoyance due rng nature of dungeons

**Improved Behavior**
add +30sec to +1min into timer per region to correlate with increased size

**Reason for change**
To remove increasing reliance of rng to supply you with 1) boss or 2) 2 chests near start of dungeon

**Comment by Logman4** [comment]
True, but it is balanced out by there being a lot more empty space in the dungeons, use the [link](https://pokeclicker.miraheze.org/wiki/Dungeons) to see more on, and since you do have more attack power the more you progress they are overall fairly balanced by your power gain if you gain power correctly.
