### ISSUE TITLE
[SUGGESTION] More hotkeys

### ISSUE THREAD

**Issue by Elanif** [pokeclicker/pokeclicker#1454]
**Current Behavior**
There is a limited amount of hotkeys/shortcut keys.

**Improved Behavior**
Hotkeys for Pokemon Day Care, Underground, Farm, accessing the Elite Four (not fighting) and more.
Maybe the pokemon day care would be overkill since there's a nicely accessible button on the right.

**Reason for change**
It's easy to misclick the little icons and pressing hotkeys like QWER would be faster and more reliable. Sometimes I'll afk for a long time on the wrong routebecause I misclick and I dont notice.

**Detailed Description**
Access the mentioned menus through hotkeys.

EDIT: I just reached Johto and there are some nice big shortcut buttons on the bottom right, so maybe disregard this.

**Comment by Twibby** [comment]
I'm upvoting this as I think Underground **really** need hotkeys to be more enjoyable. Especially when you spend most of your time switching between hammer and chisel.
Most intuitive solution that come to my mind is to use the first letter of each word :
H - switch to hammer
C - switch to chisel
S - make survey (if available)
B - Use bomb

I don't think we need a shortcut for Skip button because it's not something you do a lot ( but if really needed we can use k or even shift-S)

**Comment by RedSparr0w** [comment]
Closed via #1936
