### ISSUE TITLE
[BUG] Battle Frontier not acknowledging defeated stages

### ISSUE THREAD

**Issue by mozai** [pokeclicker/pokeclicker#1498]
**Info**
 - OS: Linux
 - Browser: Firefox
 - Version: 0.8.4

**Description:**
After leaving the Battle Frontier (either by defeat or by leaving early), i see the pop-up telling me the highest level of Battle Frontier I completed, but there's no mention of it in the logbook, and rewards are not awarded.  When I restart the Battle Frontier, it displays rewards for stages I've already passed.

**Steps to Reproduce:**
1. Go to Battle Frontier
2. See the next reward tier is for completing stage 170
3. Fight until stage 181
4. Click "Quit Battle"

**Expected Behavior:**
Pop-up saying something like "you have completed Battle Frontier stage 181," and the rewards for completing stages 170 and 180 are dispersed.  When next I enter Battle Frontier, the first available reward is for completing stage 190.

**Screenshots:**
![](https://i.imgur.com/zcUINBk.png)

**Additional Information:**
No errors on the javascript console.

**Comment by Aegyo** [comment]
This is because BattleFrontierMilestoneItem is overriding the `gain` function, so it never gets marked as obtained, and remains as the "next" milestone to unlock.

That class should be passing the reward code into the super constructor as a reward function, and leaving `gain` untouched (like the pokemon milestone is already doing).

**Comment by Aegyo** [comment]
Or rather, that is why it is still broken on develop after the latest bug fix attempt

**Comment by mozai** [comment]
Looks like it's fixed in 0.8.5
