### ISSUE TITLE
[SUGGESTION] Rework for Vitamins (Protein)

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1570]
**Current Behavior**
Protein gives +1 damage per hatch. That's it.
It's a very strong boost that gives a lot of Power to weak Pokémon because they usually have low Egg Steps and gain a lot of efficiency from Proteines.
Also there are no other Vitamins in the game.
 
**Improved Behavior**
I had an idea I want to discuss that uses the 6 Vitamins that are used for base stats in the original game and that work more like they do in the originals.
After doing the math for some Pokémon I came to the comclusion that strong Pokémon benefit more than weak Pokémon from this change. Which makes sense in my opinion.

**Reason for change**
- Proteines are too strong on weak Pokémon
- Missing out on 5 other vitamins
- This suggestion is somewhat closer to the main games
- It does not matter when you feed the new vitamins - you always get the buff for all the hatches you have done so far

**Detailed Description**
My idea is to provide 6 different vitamins (HP Up, Protein, Iron, Calcium, Zinc and Carbos). Each adding +1 to the **base stat** of the Pokémon (HP, Attack, Defense , Sp Attack, Sp. Defense and Speed).
The regional Cap could stay as 5 per Vitamin. So in Kanto you could add + 5, 5, 5, 5, 5, 5 at max to your Pokémon Stats. +30 of each in Kalos.

In the following example I will use the Kalos gamestage for the Maths because that's where most of us are currently in. 
If I do the maths wrong feel free to debunk me. 

This is the current Base Attack formula:
![image](https://user-images.githubusercontent.com/82889773/132246905-afc5352e-eeef-465f-b3ca-fc05fc11e35f.png)

Example Bulbasaur:
            'hitpoints': 45,
            'attack': 49,
            'specialAttack': 65,
            'defense': 49,
            'specialDefense': 65,
            'speed': 45,

Which leads to 53 base Attack because it always get rounded lower in the end.

So hatching Bulbasaur 1 time should now get + 13 Damage.
If you use 30 proteines you get an insane+ 43 damage for every time you breed it.

Now lets see what happens if we use 30 of each new vitamin on it:

The base values gets raised to this:
            'hitpoints': 75,
            'attack': 79,
            'specialAttack': 95,
            'defense': 79,
            'specialDefense': 95,
            'speed': 75,

This leads to new base stats of 129 Damage.
breeding it once: +32 Attack damage.

Now lets do the same on a strong Pokémon:

Example Rayquaza:
            'hitpoints': 105,
            'attack': 150,
            'specialAttack': 150,
            'defense': 90,
            'specialDefense': 90,
            'speed': 95,

Base damage: 262
Base Attack gain/hatch: +65
Witch 30 current Protein: +95

Witch my suggestion the base stats change instead to after 30 of each vitamin: 
            'hitpoints': 135,
            'attack': 180,
            'specialAttack': 180,
            'defense': 120,
            'specialDefense': 120,
            'speed': 125,

Base damage: 406
Base Attack gain/hatch: +101

Side effects:
- changing base stats allows to get damage buffs for previous hatches. I would like that, other people may not?
- 6 Vitamins, maybe 6 ways to obtain them (we also have 6 currencies 🤔 )
- buffing base stats is closer to the original
- low power Pokémon don't get the insane efficiency boost
- could make use of some original Pokémon knowlede to buff the righ stats first to gain the maximum amount of damage Buffs (more gameplay depth)
- a single vitamin is worth less. Prices need to change obv.

Let me know what you think. 😺

**Comment by GarrikFel** [comment]
This would mean implementing stats for all pokemon.  That seems unlikely to happen.  The problem is the battle system.  To add in the other vitamins, we would need to drastically alter how this game plays in order to make them useful.  

The reason why only proteins exist in this game is because there's only one stat worth considering: attack.  Pokemon don't currently use HP.  HP normally limits your progress because your pokemon need to be able to take a few hits in order to fight.  In this game, the timer handles that same function (You can imagine running out of time as all your pokemon fainting).  Without HP, defense doesn't make sense to implement.  And then there's speed... what would that do?  Maybe speed could add more time to the timer, but good luck trying to find a balance for all 810 pokemon in the game with their speed stats.  Maybe if you had a team of 6 to fight your battles, instead of a team of 810 the individual stats would matter more.  

That's not to say that we can't implement this.  But in order to do so, we need to discuss how changing the battle system benefits the game.  Right now, the game is very streamlined, and falls in line with a clicker/idle game.  It is unlikely that the entire game's battle mechanics and balance will change to account for the other vitamins.  You would need to address how adding this complexity make the game more fun.

**Comment by Ultima1990** [comment]
GarrikFel we already have all the stats in the code. They are used to calculate damage, as demonstrated above. Changing vitamins like this doesn't mean changing the entire battle system.

**Comment by GarrikFel** [comment]
I apologize.  I was looking at my downloaded version of the code, and I didn't see anything about offense, defense or stamina.  

Just out of curiosity, which file is that information in?  It wasn't in my damageCalculator.ts, or my script.min.js, which were the two spots I was looking at for damage calculations.  If someone could point me in the right direction of where these formulas can be found I would greatly appreciate it in the future, so that I don't make this kind of mistake again.

**Comment by NiCeDiCe90** [comment]
It's all in the [PokemonList](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/pokemons/PokemonList.ts)
There are all Stats and the calculation for base damage is almost at the end of the file

**Comment by Aegyo** [comment]
[PokemonList.ts](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/pokemons/PokemonList.ts)

**Comment by GarrikFel** [comment]
> 
> 
> It's all in the [PokemonList](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/pokemons/PokemonList.ts)
> There are all Stats and the calculation for base damage is almost at the end of the file

Ok, thanks!  I don't know how I missed that... must be having an off day...

**Comment by GarrikFel** [comment]
I'm having an off day, so take everything I say with a grain of salt.  I went and took a break, had some food, so hopefully I don't do anything quite that boneheaded as before.  I retain the right to admit that I'm an idiot if I miss something big again.  That being said...

Your math looks good.  However, It's not as effective as I thought at first glance.  

When looking at breeding efficiency, the numbers don't necessarily change enough.  Bulbasaur has an EggCycles of 20, so right now (with 30 proteins, rounding might be a little off) you have a breeding efficency of (43/20) = 2.15.  With your suggestion, it changes to be (32/20) = 1.6, which is a sizeable difference.  Looking at Rayquaza (egg cycles 120) it goes from .78 to .84, which is a modest improvement, but doesn't seem like it would change the meta.  

I did some sampling for other pokemon based on what I felt like looking at (note, might be some small rounding errors)

### Gyrados: 
- Old Attack: 67
- New Attack: 65
- Old Breeding Efficiency: 8.38
- New Breeding Efficiency: 8.13

### Deoxys (Defense): 
- Old Attack: 59
- New Attack: 55
- Old Breeding Efficiency: 0.49
- New Breeding Efficiency: 0.46

### Magikarp: 
- Old Attack: 32
- New Attack: 12
- Old Breeding Efficiency: 6.4
- New Breeding Efficiency: 2.4 <-- Makes sense!

### Xerneas: 
- Old Attack: 94
- New Attack: 100
- Old Breeding Efficiency: 0.78
- New Breeding Efficiency: 0.833

### Vivillon (Fancy): 
- Old Attack: 51
- New Attack: 43
- Old Breeding Efficiency: 1.46
- New Breeding Efficiency: 1.23

### Igglybuff: 
- Old Attack: 36
- New Attack: 22
- Old Breeding Efficiency: 3.6
- New Breeding Efficiency: 2.2


As you can see, in terms of breeding efficiency, it doesn't make strong pokemon that much stronger, but it does make weak pokemon that much weaker.  I don't disagree with this change, but you would get a lot of push back from it since it doesn't buff up the strong pokemon by a similar amount as it weakens others.  I would miss my hilarious buff babies.


Also, I'm not sure (it's been quite a day for me for this sort of thing, if I'm wrong, let me know) but it looks like Gyarados has the wrong number for EggCycles in the code.  It should be (320/40) = 8, and my copy (redownloaded today) lists it as 5.

**Comment by RedSparr0w** [comment]
> Also, I'm not sure (it's been quite a day for me for this sort of thing, if I'm wrong, let me know) but it looks like Gyarados has the wrong number for EggCycles in the code. It should be (320/40) = 8, and my copy (redownloaded today) lists it as 5.

The egg cycles get re-calculated from the values shown in `PokemonList.ts` based on prevolutions/evolutions/babies

----------------------------------------------------

The main thing I'm not a fan of is:
> changing base stats allows to get damage buffs for previous hatches.

From the stats both you and @GarrikFel have provided it seems like it be an overall nerf to attack gain?
Although it is hard to tell with such a small sample size.

Also worth noting there's a PR with most of a Vitamin change already implemented #1143.
_(don't remember exactly what needed doing on there, it's been awhile, think most of the discussion may have ended up on Discord)_

And another issue/suggestion to do with Vitamins #1180.

**Comment by anapple96** [comment]
I feel like for this change to work, it'll need to be buffed by percentage. Why? Because strong Pokemons already have very high base stats, +30 in all stats won't change that much when compared to +30 flat in breeding, while also nerfing 70% of Pokemon in the process, resulting in a sharp attack loss. If the vitamins work by percentages instead, the buffs/nerfs from strong/weak mon will sort of counteract each other, resulting in a similar attack spread.

**Comment by GarrikFel** [comment]
If we buff by %, where each vitamin buffs the stat by 1% it would make the weak pokemon even weaker, and buff the strong pokemon by a little more, but not by a lot (don't have time to make a full post, but Rayquaza goes from 94 --> 110, Breeding Efficiency 0.78 --> 0.91, bulbasaur 43 --> 24 BE 2.5 --> 1.2).  It's basically the same thing as the original suggestion, but a little more extreme.  We might want to bump it to 5% or more.  Will do more math after work

**Comment by GarrikFel** [comment]
So, I played around with the numbers a bit.  I think 5% would be too much.  It would drastically increase the stats of too many pokemon that it would make Kalos kind of a joke.  It's possible, but we might need to rebalance the stats of enemy pokemon to counter it.  1% is too little, it's just like the original idea in this suggestion, but makes strong pokemon slightly better, but makes weak pokemon much worse.  

I think I'm leaning towards 3%.  Using the same pokemon as before, here's what happens if each each vitamin gives a 3% bonus to a pokemon's stats (max 30 for a 90% bonus per stat for Kalos) (Might be some rounding errors)

### Bulbasaur: 
- Old Attack: 43
- New Attack: 46
- Old Breeding Efficiency: 2.15
- New Breeding Efficiency: 2.3 (Basically the same)

### Rayquaza: 
- Old Attack: 94
- New Attack: 228
- Old Breeding Efficiency: 0.783
- New Breeding Efficiency: 1.9 (Substantial Improvement)

### Gyarados: 
- Old Attack: 67
- New Attack: 127
- Old Breeding Efficiency: 8.38
- New Breeding Efficiency: 15.875 (Ridiculous!)

### Deoxys (Defense): 
- Old Attack: 59
- New Attack: 101
- Old Breeding Efficiency: 0.49
- New Breeding Efficiency: 0.84

### Magikarp: 
- Old Attack: 32
- New Attack: 7
- Old Breeding Efficiency: 6.4
- New Breeding Efficiency: 1.4

### Xerneas: 
- Old Attack: 94
- New Attack: 227
- Old Breeding Efficiency: 0.78
- New Breeding Efficiency: 1.89

### Vivillon (Fancy): 
- Old Attack: 51
- New Attack: 72
- Old Breeding Efficiency: 1.46
- New Breeding Efficiency: 2.06

### Igglybuff: 
- Old Attack: 36
- New Attack: 22
- Old Breeding Efficiency: 3.6
- New Breeding Efficiency: 2.2

### Conclusion:
All the middle pokemon will be about the same.  It makes weak pokemon weaker, but not by as much as the original suggestion.  The strong pokemon get significantly stronger, so that the meta would shift from weak pokemon + gyarados, to middling pokemon + gyarados,  But this system would allow you to use your favorite legendaries without it being almost a complete waste of time.  A lot of people have middling pokemon as their favorites, so you can probably just focus on your favorites and make good progress in the game.

This does make Gyarados even more ridiculous.  However, with the formula we're suggesting (where vitamins get applied to the base stats directly) either it ends up as a net loss in attack, or Gyarados becomes even more ridiculous.  The problem is the division by egg cycles.  With the new formula, you're dividing by EggCycles*4, and since EggCycles has kind of a large variance to begin with, and Gyarados' whole deal is a ridiculously tiny EggCycles, there's no avoiding it with this line of thought.  We would have to change the formula to something other than just (baseAttack*0.25)/EggCycles

**Comment by Aegyo** [comment]
Looks like we have gone in a different direction for new vitamins and this issue is incompatible, going to close but feel free to argue why actually this is way better and I should re-open it.
