### ISSUE TITLE
No Es Un Bug Es Un Problema Siempre Que Juego Como No Gano Los Token Suficientes No Puedo Continuar Mi Aventura[BUG] 

### ISSUE THREAD

**Issue by JaredUwU** [pokeclicker/pokeclicker#1632]
**Info**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari, Firefox]
 - Version [e.g. `v1.0.0`]

**Description:**

**Steps to Reproduce:**

**Expected Behavior:**

**Screenshots:**

**Additional Information:**

**Comment by PixLSteam** [comment]
![image](https://user-images.githubusercontent.com/21047644/140322370-590c4f4f-f4ae-4a77-8ed9-556d77729b0d.png)
I'm not sure if I understand this correctly since I have to use google translate, but if you're talking about the tokens in the image above: you have to catch Pokémon to gain them. Select a Pokéball for "Already caught" like this: 
![image](https://user-images.githubusercontent.com/21047644/140322667-fd351620-e52f-4c2d-a49e-3136fc7c84f8.png)
