### ISSUE TITLE
[SUGGESTION] New Challenge - "Harder Dungeons"

### ISSUE THREAD

**Issue by NiCeDiCe90** [pokeclicker/pokeclicker#1700]
Some of the newest additions to the game makes the game (dungeons) too easy for people who love the insane challenges like A6CSRQ (or now A8C i guess).
Maybe we can make it harder again. 

So here is my Idea:
Add a 9th challenge: "Harder Dungeons"

-> removes all dungeon shrinking
-> removes "Flash" effect on 200+ clears

-> removes all items with a weight of 2 or lower

Not sure about the last one though...
The last point is a bit weird for "All Challenges" since they would get mostly battle items again that they can't use.

The Problem for SRQ Challengers are the high numbers of the weight 1 and 0 Items you get after 10k++ clears. So removing these and let them only get "useless" Items might be the way they want to play.

**Comment by scolpitts536** [comment]
Instead of removing dungeon clears make it kalos, alola, and galar can go down to 9x9 or we won't finish the dungeons when alola and galar comes out, I would keep flash, and make it remove item weight with 1 or lower that way we can get small restores and its only underground items and small restores and still excludes eggs, fossils, and evo items.

**Comment by jk13pclick** [comment]
You don't need to remove the items, just adjust the (currently) existing max clears restriction on the weight formula. Ie: Max it at 10 and low weight items will still be hard to get even at 1000 clears. Removal of the Dungeon perks is good, maybe even bump the health modifier from opening chests.

**Comment by NiCeDiCe90** [comment]
closing this in favor of the new suggestion for challenge reworks: #2332
