### ISSUE TITLE
[SUGGESTION] Described capture conditions for already caught Pokémon

### ISSUE THREAD

**Issue by jaahay** [pokeclicker/pokeclicker#1745]
Provided more Pokémon context and content as it pertains to capture conditions.

**Current Behavior**
Opaque as to where Pokémon may be caught

**Improved Behavior**
Detailed description of where Pokémon may be found and caught.

**Reason for change**
Better game play experience. Quality of living change.

**Detailed Description**
Per caught Pokémon describe where it may be found and caught:
* route[s]
* dungeon[s]
* shop[s]
* evolution[s]
* wandering
* safari
* battle frontier
* hatchery -> Pokémon
* hatchery -> egg[s]
* hatchery -> fossils
* farm
* special quest
* special / seasonal event
* discord

Also, exposed the reversed direction; Pokémon by route, by dungeon etc.

**Comment by amative1** [comment]
Sorry, to clarify: you're looking for the Pokédex to show you where you can catch specific Pokémon?

**Comment by jaahay** [comment]
Yes (for Pokémon that have already been caught)

**Comment by amative1** [comment]
So what is the benefit to this? Once you've caught a Pokémon, you no longer need to know where it is (since you already have it). Knowing where one specific already-caught Pokémon is won't help with any quests or anything like that. Also, all Pokémon locations are based on original-game data (so for example Pokémon Red/Blue feature Pidgey and Rattata on Kanto Route 1, so that's what you'll find in Pokéclicker). Also, some Pokémon are found in only one location, and some in many locations (across many regions), so this would require a lot of development work.

Not saying "no", but I don't think there's any benefit to this at this point.

**Comment by NiCeDiCe90** [comment]
It could help to find the best options to force a shiny... But idk if it's worth the effort to code this.

**Comment by Farboo171** [comment]
This info is on the wiki now, closing.
