### ISSUE TITLE
[SUGGESTION] Allow eggs and fossils on the hatch queue

### ISSUE THREAD

**Issue by hugojmaia** [pokeclicker/pokeclicker#1775]
Not much to talk here, other than the inconvenience that is to first empty the queue, then hatch one of the eggs to free a slot, to then be able to place either an egg or a fossil to be hatched and finally fill the queue back up with mons for breeding.

**Screenshots:**

![image](https://user-images.githubusercontent.com/8614893/149643979-e5c6e8d7-9aed-4a4b-9b0a-ea1d6db0541f.png)

**Comment by NiCeDiCe90** [comment]
duplicate of #1362
I don't think this will get accepted. It would make mass breeding of egg/fossil Pokémon too easy

**Comment by amative1** [comment]
The main issue is that items added to the queue can be _removed_ from the queue. So adding a water egg gives you info about what Pokémon is incoming. Also, the queue would need to be completely reconfigured to add eggs/fossils removed back to their respective pools (rather than just back into the active Pokémon list).

**Comment by mloler** [comment]
How about not allowing them to be removed from queue? just like when they get steps?

**Comment by RedSparr0w** [comment]
closing as duplicate of #1362
