### ISSUE TITLE
[SUGGESTION] Let us leave the Battle Frontier without forfeiting all the rewards

### ISSUE THREAD

**Issue by ZargoGames** [pokeclicker/pokeclicker#1905]
Treat leaving the Battle Frontier as a loss instead of wasting all the time we spent in there.

**Current Behavior**
If you leave the Battle Frontier without losing, you lose all the rewards you would normally gain when you eventually lose.

**Improved Behavior**
Treat leaving the Battle Frontier as a loss, and give us the rewards we would have received it we lost at that point.

**Reason for change**
Going into the Battle Frontier is a large time commitment because I know that if I want to get anything out of it, I'll need to stay in there for a long time. Letting me leave without sacrificing anything I've already earned would encourage me to use the Battle Frontier more often. The rewards for doing the Battle Frontier are already pretty meager once you've completed all of the challenges, so there's no reason to additionally punish players that want to just dip into the battle frontier for a few moments then go do something else.

**Detailed Description**
Same as above.

**Screenshots:**
Not really applicable.

**Comment by Ultima1990** [comment]
Letting players leave with their earnings early encourages grinding the low and easy floors for maximum BP/s, when what we really want is to encourage climbing as high as possible. Let me propose an alternative:

**Checkpoints.**

Give the player a checkpoint every 100 floors. Once they lose and restart the climb, they will start one checkpoint _below_ their highest. For example, if your highest checkpoint is at floor 100 you start at the bottom. If your highest checkpoint is at floor 200 you start at floor 100. Of course we then only give BP for the floors they actually clear in a run. If you start on floor 100 you don't just get the BP from floors 1-99 for free.

You start one checkpoint below your highest to avoid people getting stuck with very few floors to get BP on without needing significant grind. As an example of what would happen if we didn't do this: A player might climb to floor 105 and fail. Now, with a checkpoint at 100, they only have a couple of floors to climb before they hit that ceiling again, giving them very few floors to actually play on. By making players start one checkpoint below their highest they will always have at least 100 floors to play and get BP on.

In the end this probably won't increase BP gains much even though players start closer to the higher value floors, since players will be skipping the early easy fast oneshot high BP/s floors. It will result in shorter runs though, which is the goal. This, combined with the speed boost on cleared floors, should bring you back to your ceiling fairly quickly, especially compared to how it is now. Shorter runs hopefully means people are less discouraged to enter the frontier, which in turn hopefully results in players choosing to climb higher, which is what we like to see. As opposed to the current state, where players kind of don't want to climb higher because climbing higher takes longer.

Maybe these runs would still be too long. Could maybe consider giving checkpoints every 50 floors instead. That's up for debate.

**Comment by Razrushil** [comment]
Checkpoints might be a bad way to go unless you can choose which passed checkpoint to start from. The man reason people use the Battle Frontier is for efficient breeding, so the checkpoint would ultimately make you gain significantly less BP and take away the ability to breed more efficiently. 
I'm not sure if it would be feasible or a good idea, but possibly changing the Battle Point formula to (stage completed)^3 / 100 instead of (stage completed)^2 / 100, multiplying all BP costs by 1000, then gaining BP at the end of each stage ((3s^2 - 3s +1 )/100) might work better. It would ultimately make the BP gain lower (relative to costs) than current until floor 1000, but the gains will be skewed much more heavily to later stages than now, so only clearing the early stages will be less efficient than it currently is. Also, this will make BP costs and amounts comparable to pokecoins and DT, so it won't look too out of place.

**Comment by Aegyo** [comment]
Checkpoints have been added to the BF now, I think this can be closed.
