### ISSUE TITLE
[SUGGESTION] Add the Pokemon League shop to the Shortcuts once you've reached it

### ISSUE THREAD

**Issue by ZargoGames** [pokeclicker/pokeclicker#2066]
Add a shortcut to the Pokemon League Shop once you've reached it. That way you don't have to leave your current map location to buy Master Balls and Proteins.

**Current Behavior**
You have to leave your current map to buy Pokeballs and Proteins

**Improved Behavior**
You can instantly visit the Pokemon League Shop once you've reached it so you don't have to leave your current route.

**Reason for change**
It would speed things up.

**Detailed Description**
The Poke Mart gets its own shortcut that allows you to buy standard items like Pokeballs and Battle Items without leaving your current route, and I think it would be helpful to do the same for the Pokemon League Shop. It's not a big deal, but it would be a nice QoL improvement.

**Screenshots:**
n/a

**Comment by Kays** [comment]
Perhaps the existing Poke Mart popup can be updated to have tabs similar to the Berry Master shop popup (Shop, Trades). This one would have Shop, League, Berry Master, perhaps. I think the logic for the League tab to show up is if the player has access to the Port and is a Kanto champion rather than the region champion because access to the port allows me to travel to a previous region to buy them, albeit inconvenient. Berry Master would also be nice to have, but maybe a bit trickier because not every region has a Berry Master shop.

**Comment by YaibaToKen** [comment]
The Berry Masters could each have their own button, displayed after you've unlocked them in their regions.
However, from a UI/UX perspective, I'd rather have the League Shop be its own button in the shortcuts, instead of a tab in the Poké Mart modal. 1 click vs 2 clicks each time you need the League Shop.

**Comment by Ultima1990** [comment]
Shortcuts are evil and for lazy people. The map is the main interface. No more shortcuts! In fact, less shortcuts!

**Comment by YaibaToKen** [comment]
> Shortcuts are evil and for lazy people. The map is the main interface. No more shortcuts! In fact, less shortcuts!

😢 While the map is indeed the main interface, having to interrupt the current activity (a dungeon, battle frontier, a gym fight, etc) to acquire protein can be tedious and cumbersome, specially since those items won't have direct bearing on the ongoing activity (even for protein since pokémon breeding continues regardless of being in battle frontier or another activity).

**Comment by Farboo171** [comment]
Different shops have different things, and the shortcut shop is the department store intentionally. Closing.
