### ISSUE TITLE
[SUGGESTION] Scaling quest 

### ISSUE THREAD

**Issue by Andy-William** [pokeclicker/pokeclicker#2088]
**Current Behavior**
Quests currently pick from a list and randomly assign the numbers within certain values depending on the type.

**Improved Behavior**
The range of possible values should scale with quest level. This at least includes quest requirement, quest point(QP) reward, and refresh cost. For refresh cost, I also suggest for it to increase the price for every usage (resets daily).

**Reason for change**
The optimal way to farm QP is to do the fastest/most rewarding quest and refreshing very often. QP is mainly used for masterballs but other currencies are just easier to farm. 

With increased requirement, reward, and incrementing reroll cost, quest becomes actual sidequest. The player will be incentivized to increase quest level for more questing convenience (less active rerolling) rather than just mindlessly rerolling quest to get the desired outcome.

**Detailed Description**
Just increase the numbers, maybe add a hard cap.

**Screenshots:**

Something like this, some numbers will need rebalancing.
![image](https://user-images.githubusercontent.com/6039182/165625307-c27e7121-3af4-4dae-aabf-17b5c2c1f5c0.png)

**Comment by Kays** [comment]
(⊙＿⊙')

Harvest 30 Petaya berries!? That's crazy. A lot of those are pretty annoying because they require too much time investment compared to the current quests. I can farm 8-9k faster by rerolling resets with the current quests faster than grind most of the ones in your pic.

The current quests are okay to an extent. The way I do them is - I just do them along with achievements. For example, if I get a dragon gems quest, I run through any dragon gyms I still need achievements for or dragon dungeons like Dragonspiral Tower that I have incomplete achievements. There are only like 4 categories of quests that are absolutely garbage because you have to go out of your way to do them and doing them stalls out progress.
1. Harvest specific berries quests are terrible. When I have my Chople farm setup, I'm not breaking that to plant specific berries. That's not a good quest.
2. Capture specific Pokemon types. This one is not a bad idea, but the rewards is too low to justify the time spent on specific routes, especially when those routes are already done per achievements. Even if the rewards are decent, it can be pretty hard depending on the region. Like capture fire types in Unova is annoying because I can only think of Darumaka off the top of my head and that thing has a rather low catch rate.
3. Defeat old dungeon quests are terrible, especially if I already completed the 500 runs for that dungeon. That's just a waste of dungeon tokens.
4. Defeat a specific amount of Pokemon in an earlier route. Like defeat 400 Pokemon in Kanto would be inefficient to do if you're already in further regions and have completed the route achievement for that route.

These are okay, but they're a bit annoying.
1. Using Exp. Share feels really bad because I really don't need it. Right now, when I get this quest, I do it but I would farm out a dungeon with it on because I don't get money from dungeons unless there are trainers.
2. Collecting Fairy gems is slow until Kalos, so that quest is not worth the time doing pre-Kalos. It's hard to find a dungeon that has Fairy-type bosses as well.

Rather than increasing the amount and making the quests take longer to accomplish, it would be better to make them more convenient and less of a chore. Like if I'm in Unova, I don't want to go back to Kanto to defeat 400 Pokemon in a route, especially when I'm done with Kanto route achievements. Also, I don't want to mess up my Chople farm, or whatever farm setup I have, to plant a random, mostly useless, berry. Mostly, the refresh is used because most of the quests are inconvenient and the money spent to refresh is simply more time-efficient than doing some of the quests. The amount of QP isn't the problem. Even if the quests gives me 10k QP to farm 3k kills in a Kanto route, I would refuse to do it.

**Comment by Andy-William** [comment]
Exactly, the current quest is just "rerolling until I get whatever I'm doing". You still can skip quests with my suggestion. It's just more costly so you only skip because of necessities, not convenience. Rather than resetting 100x in an hour, wouldn't it be better if the numbers are x100 instead?

**Comment by Kays** [comment]
> wouldn't it be better if the numbers are x100 instead?

Not necessarily. Larger numbers are only better when they make sense in some context. For example, 2500 Dragon Gems is maybe. That's fighting a Dragon gym leader 100 times, provided 5 Dragons per battle. That's not terrible unless you already finished the 1000 gym battle achievements, in which case, this is quite inefficient. The current ones involving gems is like around 500 at the highest amount, which is only 20 runs. The difference is that it's a bit more versatile too because 500 is low enough such that you can farm dungeon bosses of the proper gem type as well, provided you have dungeon achievements left to do. At 20 gems a piece, it'll take 25 encounters, which is reasonable. If it's 2500, 125 encounters can be rough. That's almost like the entire 500 dungeon runs provided the bosses aren't only of said type. And it's not a "oh, you got through 50% of the quest, so the game will reward you with 50% of the rewards". It's an "all in or nothing". Not everyone can spend hours on end grinding long quests, so having them all scaled up also makes them less practical. It's a similar complaint people have with Battle Frontier, where quitting gives no rewards and the runs take too long for some people to leave the game running nonstop for many hours.

**Comment by Andy-William** [comment]
I see what you're saying is to rebalance the quests. However that is not the point of this suggestion. Feel free to make a new suggestion on how to rebalance the numbers.

**Comment by Kays** [comment]
This is just my feedback or 2 cents on your suggestion. I don't think it's a bad suggestion, but the numbers may be too extreme and striking a balance can be very hard as it scales up. Personally, I don't have an issue with the way quests work. I don't mind refreshing it.

**Comment by amative1** [comment]
Approved. Moving to master ticket.

**Comment by Aegyo** [comment]
Re-opening, master ticket replaced with a Project

**Comment by Farboo171** [comment]
This is the new unified "rebalance quest point gains" suggestion, closing others as duplicates and referencing here

**Comment by RegisCoaxans** [comment]
Beware, this suggestion does not refer to an actual rebalance of the quests.

**Comment by Farboo171** [comment]
Several quests were rebalanced to include scaling, several others were evaluated for scaling and it was not added. closing.
