### ISSUE TITLE
[SUGGESTION]  Highlight the rares drops in dungeon 

### ISSUE THREAD

**Issue by Seikatsu13** [pokeclicker/pokeclicker#2178]
I was wondering if Highlighting the rares drops in dungeon would be a good idea ? I'm sorry if thats was already asked, i'm not familiar at all with github so i didn't found my request anywhere or i didn't searched very well.

**Comment by Kays** [comment]
What do you mean by "highlighting"? There are notification settings for them:

- Enemy Pokémon dropped an item
- Item found in dungeon chest

Are those insufficient?

**Comment by abourrier** [comment]
A sound alert would be nice for rare drops. The silent notification is not really noticeable when you focus on the dungeon layout to complete it quickly.

**Comment by polak0v** [comment]
Some suggestions related to rare dungeon drops:
* Add possible items drops from the dungeon chests in the dungeon interface, with indication if rare or not (`weight` < 2). No need to show hold items from pokemon as it is already in the pokedex.
![image](https://user-images.githubusercontent.com/68350634/170579739-5c54bd72-caa2-4542-95b1-aaa09d8b3c45.png)
* Add another notification under `settings/notifications/items`: "Rare item found in dungeon chest". Replace the other one by "Common item found in dungeon chest". 
Then we would not be spammed for crappy items, and missing the actual rare drops (because the notification queue fills up too quickly).

I would be happy to create a pull request but I don't know javascript...

**Comment by CorgiOnNeptune** [comment]
> 

I have an implementation in progress for this on my to-do list.
