### ISSUE TITLE
[BUG] Impossible to get Cyndaquil with egg

### ISSUE THREAD

**Issue by Tadaaam** [pokeclicker/pokeclicker#2330]
**Info**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [e.g. `v1.0.0`]

**Description:**
Hello, i bought many fire eggs to get Cyndaquil the fire starter form Johto and i haven't get it. I don't know if it's a weak pourcent chance to get it but if it's a bug i tell you with this post.

**Comment by Qwertypop04** [comment]
RNG is not a bug.

**Comment by Tadaaam** [comment]
Ok thanks ! It's a little %chance ?

**Comment by dragonkin550** [comment]
You have a 1/8 chance of getting it. If your luck sucks, you might need 20 or 40 or more eggs to get it

**Comment by NiCeDiCe90** [comment]
They way how these eggs work (if I remember correctly) is that you always have a 50% chance of having a Pokémon of your highest region and 50% for all previous regions.
So since there are 4 Pokemon that come from fire eggs in Johto it is a 12.5% chance to get it.

Getting Tyrogue is a 50% chance for example, since it's the only fighting Pokémon in the regions egg pool.

So it's true that the fire exclusives in Johto are the harder ones to obtain. But it's not a bug.
