### ISSUE TITLE
[SUGGESTION] Add Obtainable Mega Pokemon

### ISSUE THREAD

**Issue by Cobraximus** [pokeclicker/pokeclicker#2629]
**Description**

Add in Mega Pokemon? Lysandre has a Mega Gyarados and Diantha a Mega Gardevoir in game, so why not add in obtainable Mega Pokemon for the player?

**Comment by NiCeDiCe90** [comment]
It's planned to add megas as a feature at some point. That's why they are already in the code and got added to the team of Lysandre and Diantha.
They are not available for the players because we have not decided **how** to add them. We want them to be something special and not just +1 Pokémon in the list.

**Comment by Jaaslet** [comment]
Well, we think we know how we want to add them, but held items need to be merged, before we can start that project.
I will close this issue, as it does not add anything
