### ISSUE TITLE
[SUGGESTION]  hotkey for the dock

### ISSUE THREAD

**Issue by hellonavi** [pokeclicker/pokeclicker#2767]
**Improved Behavior**
create a hotkey for the dock (maybe D by default?) so that players do not have to manually find and click the dock to travel between regions

**Reason for change**
simple quality of life. i really like the ease of having hotkeys for things like the day-care and farm for example, and it makes performing regular tasks in the game a lot quicker. i think it would be great to have a quicker way to travel, since i find myself going between regions fairly frequently between the story, quests, and getting achievements. some have stated that finding the dock in each region isn't the most intuitive thing either, so this would help with that problem as well.

**Detailed Description**
adding a hotkey command that opens the dock travel menu, removing the need to click on it every single time

**Screenshots:**
N/A

**Comment by Ultima1990** [comment]
No. This is basically the same thing as adding a dock shortcut. The map is the game's main interface. Any shortcut detracts from that. I kinda wanna get rid of the other shortcuts too some day.

**Comment by zyx-xyzzy** [comment]
> I kinda wanna get rid of the other shortcuts too some day.

OK, I can accept the dock-shortcut concept being established as not happening, but _this_ would be a huge downgrade IMO. Unlike with the dock situation, the existing "shortcuts" are in practice more essential to the gameplay flow than their name implies:

- The current "on-map" underground and farm locations are tough to keep track of due to being placed in arbitrary locations that differ per region and being small and dull enough to blend into their surroundings (problems notably _not_ shared by the docks, which are easy to learn/remember as always being in the "port town" that you're dropped off in when you change regions, and are made visually distinct by jutting out against the water). Also, having to stop to look for their map locations whenever you want to use them would be especially inconvenient for the farm given how time-sensitive it can be!

- The shop shortcut offers extra utility/QoL not found in the regular map by allowing you to shop without having to leave the route/dungeon/frontier you're in, and in having a full stock of the standard purchasable item loadout so that the transactions you're going to be making frequently (as opposed to, say, trader/QP purchases) can be taken care of with no hassle, rather than having to keep track of e.g., "hey, which towns in this region sell Small Restores again...?"

- This is admittedly getting into nitpicky/argumentative territory, but isn't the whole notion of "the map is the game's main interface" kind of arbitrary to begin with? The UI of Pokéclicker is absolutely stuffed full of menus, lists, and dropdowns for the player to reference and micromanage; the map is merely a single one of these elements with a specific, narrow use like the rest of them (in this case, to move between and to check the completion status of routes/towns/dungeons). Just because the Day Care is visitable on the map doesn't mean anyone thinks removing the Hatchery sidebar would be an improvement to the game just because it would increase the importance of the map, for instance (or, well, at least I sure hope they don't!)
