### ISSUE TITLE
Replace regional debuff

### ISSUE THREAD

**Issue by Ultima1990** [pokeclicker/pokeclicker#2788]
This is not something I definitely want to do, but it is something I have been thinking about.

The idea is to replace the current percent based regional debuff with a damage cap. There would just be a limit on how much attack a mon from outside the region could contribute, tho I think type/gem calculation should still happen after the cap. I can see a couple of upsides:

- It'd really force the player to switch to using that region's mons. No amount of breeding Kanto mons is gonna give you more damage in Johto once they are capped. This is, after all, the intent of the regional debuff.
- No one mon is king for ever. Gyarados might dominate in Kanto, but you'll have to find a new mon in Johto and onwards. Though frontier would still count all mons fully, so Gyarados would still dominate there. Unless #2615.
- The way we release regions results in a lot of overbreeding. Players with nothing to do sitting on Poni Gauntlet grinding out those shiny breeds are gonna steamroll Galar no matter how hard we make it, and at the same time we have to think about the new player experience. This way we eat two birds with one scone, overbreeding will not affect Galar damage significantly and so we can balance with that new player in mind.

I think this would work especially well when combined with #2466, especially the part about the first couple of routes being _easier_ than they currently are, to allow players a real foothold in the new region and access to enough new mons before that cap on old mons starts to hurt too much. Also any overbreeding would still contribute to Frontier damage, as well as any other battle facility we might come up with in the future (#2485).

Again, I'm not dead-set on implementing this at all. But it is something I've been thinking about, it might be good for the game. I want to discuss it.

**Comment by space244-hub** [comment]
Yeah ngl i don't really get why the regional buff scales the way it does. You have more non region attack and you lose less of it to the debuff with each region so the new pokemon attack gets heavily diluted by both especially as you progress. By capping the damage you should be able to cut down on the non region bloat. I suppose the downside is that you can't make new regions jump up in hp as much(maybe to show difficulty increase) but i think it would have the added benefit of letting click attack catch up since it feels like its getting severely outpaced currently.

That said one other thing i'd like to add is making the cap scale with pokemon caught. In kanto each new pokemon can add a lot to your attack because you don't get as much exp and can't breed as fast. However in later regions between breeding completely taking over pokemon attack gain and the non region attack being such a huge amount catching a new pokemon barely changes attack and might not even be worth one breeding queue. What i'd suggest is each new region pokemon caught would raise the new damage cap(like going from 1000 to 1100) so you effectively gain a nice big chunk of attack with every new catch. Could also make it so when you complete the region's pokedex the damage cap is removed so you can have a much easier time farming for achievements like dungeons or gyms.

Last thing as food for thought. Pokerus and EVs are an interesting system but i can't help but feel like you'd have more attack than you know what to do with if you ever tried to max all the pokemon's EVs. Maybe make the EV bonus apply to the damage cap so it has another use as a sort of reward for later regions if you spent more time catching pokemon.

**Comment by Tyr49** [comment]
I think a scaling cap makes sense, but i would say a cap increase per region would be better.
Further, personally I think that instead of a flat cap a multiplier would make sense. i.e. in Johto you can have 2x base attack as attack from other regions, in Hoenn 3x and so on.

**Comment by RegisCoaxans** [comment]
I like the idea of capping mons instead of only reducing their attack. The associated challenge would feel less of a encouragement to grind.
I had several ideas on how to make it work nicely but I could not figure out a proper way...

I would still add something to the discussion as a fuel : could badges be part of that new scaling ? They become useless at scaling once Kanto is done but they could greatly contribute on later regions when a new cap-thing comes in action as they nicely indicate the progression.

**Comment by Tyr49** [comment]
it could fit into my suggestion. Each badge gives 0.125 onto the multiplicator until with the eighth badge you arrive at the max for the non region mons
For example: You start with 1x Base attack for Kanto mons in Johto. The first Badge gives you1.125x Base attack. Second gives1.25x Base Attack and so on. Until you reach 2x Base attack with the eight badge.

**Comment by Ultima1990** [comment]
> For example: You start with 1x Base attack for Kanto mons in Johto. The first Badge gives you1.125x Base attack. Second gives1.25x Base Attack and so on. Until you reach 2x Base attack with the eight badge.

That's the exact opposite of my intent. With this Kanto mon's relevance in Johto increases as you progress, with them getting stronger the more badges you earn. What I would like to see is for Kanto mon's relevance to be at maximum at the beginning of Johto, allowing the player to catch new mons and get a foothold in the region at a reasonable pace, but then at some point the capped Kanto damage really isn't gonna cut it anymore and you _have to_ rely on Johto mons.

**Comment by Tyr49** [comment]
Yeah a reward in relation to different mons for getting Badges just isn't doable then. Maybe one could reward a step multiplier for the regions mons as a result for beating gyms.

Also my 2x Base attack attack cap would have been way to high anyway. 
Instead I propose a 1.1x Base attack cap, giving you a starting attack of 13.630 ( if all mons were bread to have 1.1x their base attack). It would get you past Whitney, but one would still need to get about 5k worth of damage for Morty. This shouldn't be possible by simply catching all mons possible until clearing his gym.

**Comment by space244-hub** [comment]
Hmm i suppose that my increased cap as you fill out the pokedex would run into a similar problem of making non region more important as time goes on although lessened because its still tied to region pokemon.  Not sure if it could be fixed with tuning or not. Also depending on how the new regional debuff works out you may want to decrease enemy hp which is fine since a large part of why its so high is probably because of the non region attack bloat.

Ultimately one of the problems is that base attack doesn't vary that much among pokemon and breeding can very quickly overwhelm it. I suppose you could consider the opposite as a solution instead of capping damage of non region pokemon you could make a mechanic that has native pokemon get a starting boost to their attack but not really sure what you'd tie it to.

**Comment by xslk** [comment]
Is there a way to limit the damage from old region pokemon to the route health of the second or third route of the new region? It gives you enough of a cushion to have more than 1 route option but not enough damage to progress too far with dungeons and gyms. 

You can lock the unfiltered damage for the previous region to be after obtaining the first or 2nd badge

**Comment by linkdest** [comment]
My idea is nerf the breeding efficiency. The breeding effiency gets worse each new pokemon from the next region you get.  When you get to Hoenn, the Kanto pokemons can't get worse than your efficiency with a full Johto dex. I think this option is good because people can get attack with their favorite pokemon, but it would be very slow.

Doing that with current debuff is tough, probably changing all debuff from 50% would be a good option (like your issue).

**Comment by RegisCoaxans** [comment]
I mentioned badges but it would just be the same as the current debuff mechanics...

However, I like the idea of the debuff being a scaling cap to attack, based on base attack.

For example, Kanto would make non-regional mons capped at 1 time their respective base attack, Johto would make it at 2 times their base attack, Hoenn at 3 times their base attack, etc..
Those values just stand for explanation sake as they are not balanced, the scaling must not even be linear.
Of course, it would be a soft cap : breeding the pokémon beyond its regional debuff should always increase its attack and the reduced attack would be computed on the fly : no problem with BF, then.
Either the cap increases with proteins or not is up to the dev. In my opinion, it should not because those do not make the pokémon stronger, only make it strengthen faster.

This cap could as well be a flat regional value for each pokémon. But I think that it would end up making not difference between what a weak debuffed pokémon a strong debuffed pokémon could be worth each in the total attack, which is very bad; whereas my first idea confirms the legendary pokémons as the strongest ones despite amongst the debuffed pokémons.

In addition, here are the total base attacks of the pokémons (but including alternative forms, event pokémons and even the few which still are unavailable) of the previous regions for each new region : 15600 in Johto, 26300 in Hoenn, 39300 in Sinnoh, 56900 in Unova, 74200 in Kalos and 85200 in Alola (and 100000 in Galar !).
It obviously could not stay still as it looks too strong for Johto and too weak for Sinnoh and after.

**Comment by space244-hub** [comment]
I'd argue that any cap that increases will fall into the same problem as current debuff where it changes the scaling to exponential since you'd naturally increase it as you catch more pokemon and then you'd get even more from them if the debuff increased the cap as you go. You just end up with really bloated numbers for not much reason and click attack and new pokemon attack ends up falling woefully behind. Or it just ends up being so low you might as well not add it. 

Breeding is a rather mindless mechanic so it feels a bit more justified to force the player to breed johto pokemon to get through johto, hoenn pokemon for hoenn, etc. Not a lot of point letting non region pokemon compete due to some quirk with scaling or giving them reduced breeding but could still theoretically hit high enough attack to matter. If you want to make the top percentage of rattata go for it but that doesn't mean the game should be balanced around that. Breeding being as dull as it is, is part of the reason i wanted to introduce an attack bonus to caught pokemon as you progress. Since less breeding for more intelligent play feels like a common sense mechanic for this game.

I agree that making the cap scale based on base attack is a more interesting mechanic than a flat number if a bit harder to balance around. Also does partially resolve the weird issue that legendary pokemon are somehow the worst pokemon in game since their breeding efficiency is the lowest. 

Also to respond to linkdest specifically breeding efficiency is directly related to attack so you achieve the same effect by just limiting attack like the current debuff. Specifically targeting efficiency also would make it weird to keep track when you remove the debuff for battle frontier. You could easily implement by reversing how the debuff scaled so 70% at johto and 30% at alola. That said for your suggestion specifically you'd also get the really weird use case where you'd want to catch none or very few of the new region pokemon to benefit from high efficiency previous region pokemon. You'd also have no real way of dialing back the effect of super buff non region pokemon

**Comment by Ultima1990** [comment]
Having thought about it a bit, do think gems and EVs should apply _after_ the cap, meaning there is still this small way that you can boost the damage of mons from other regions. They are simple multipliers, shouldn't be hard to do.

Other than that, I'm currently thinking of not having a cap that scales in any way. Currently the debuff scales with unlocked regions. The more regions you've unlocked, the weaker the debuff becomes everywhere. I say the cap should not do that, but I also say that one cap won't work everywhere. A reasonable cap in Johto would get you nowhere in Unova. So I think each region should have its own cap that does not change. A cap that, assuming a majority of your mons are at the damage cap, should let you comfortably get 1 or 2 badges before you really have to start focusing on breeding native mons. Should hopefully mean you have a reasonable set of native mons available.

I hadn't even thought about what the cap should be based on. Initially I was just thinking of a flat cap that is the same for every mon, but strong mons should be stronger, right? And weak mons weaker? I think basing it on base damage could be a decent idea. A cap that is the same for every mon is easier to code and balance tho. Just means weaker mons take longer to reach the cap. Or actually maybe they all reach cap at around the same time, since weaker mons tend to be more efficient... Will have to think about that.

**Comment by olso4722** [comment]
This is definitely an interesting idea. It would be pretty awkward when you get to Kalos and there are so many routes that are mostly older mons. It might require a change in what counts as a regional mon. Maybe mons found in that region are uncapped regardless of where they're first found.

**Comment by Farboo171** [comment]
Related to the closed and deleted #2102 , closing.
