### ISSUE TITLE
Suggestion: Events for Golden ho-oh from episode one, shadow mewtwo, meta groudon from the jirachi movie (that isnt actually a groudon), magquaza, primal dialga, the original dragon, ashchu, and missingno (and its forms)

### ISSUE THREAD

**Issue by CaptainPokemon01** [pokeclicker/pokeclicker#2936]
It would be cool if in the game there was an event where you could get the golden ho-oh from episode one. 
It would also be cool if there was an event to get shadow mewtwo from pokken tournament.
an event to get that amazing fake groudon (called meta groudon) from that jirachi movie
an event to get the fusion magquaza that we see in one of the episodes since it's cool 
an event to get primal dialga from mystery dungeons since primal dialga is cool though it would probably be added alongside the megas and the primals and stuff like that if they ever get added.
it would be cool if we had an event or some code to get ashchu from that time when ash got turned into a pikachu.
it would be cool if not already a thing if there was an event to catch missingno and its forms since they are cool mons
and it would be amazing, if you guys decide to do it, if you had an event or some code thing in unova to get the original dragon from before it got split into reshirem, zekrom and kyurem

**Comment by Osheyking** [comment]
Like the idea also like shadow pokemon from those pokemon gamecube game in like a quest line

**Comment by Aegyo** [comment]
For these kind of alt forms we don't give approval until there is a full suggestion for a questline or something they would be part of, so I'm going to close this but a few of the ones you mentioned have had some proposals made since you made this issue:

Golden Ho-oh is included in a proposal for a Zenith Marshadow quest
Shadow Mewtwo is mentioned in the idea for a Pokemon Unite region #3649
Meta Groudon has been added to the game
