### ISSUE TITLE
[SUGGESTION] new team rocket quests

### ISSUE THREAD

**Issue by Matipou-git** [pokeclicker/pokeclicker#3103]
a new team rocket quest to "find an defeat" jessie and james

**Current Behavior**

none
**Improved Behavior**
 a new questline

**Reason for change**
 i think it would add a neet expension of team rocket lore

**Detailed Description**

1. go and get the quest on the bulletin board: "getting rid of team rocket"
2.  the player will have to find team rocket jessie and james around the maps in their meowth hot balloon or submarine magikarp. their teams would be made of team rocket pokemon and a meowth, it could change depending of their regions or lore they are related to.

3.  after completion of quest or after defeating them, the player will receive either a special disguised meowth or variant-different team rocket related pokemon, or getting the pokemon they were trying to steal

**Screenshots:**

![Capture d’écran, le 2022-10-02 à 20 14 58](https://user-images.githubusercontent.com/76797282/193483185-a3091019-a64a-42a6-8c2c-2ce5a1ad4a7d.png)

note: those are only the idea of what could be their meowh hot balloon and magikarp submarine, they will have to get detailled and reajust sizes to fit on the map

**Comment by WizardSpriter** [comment]
This seems interesting! 
Just wanted to let you know if you're not aware, you fight Jesse and James as a part of the "Team Rocket's Pinkan Theme Park" questline. 
But, still, I think this is a cool idea.
I made this sprite of a Meowth in a Team Rocket costume- not saying that this is the best option for a gift for the questline, especially since if this were to appear in Pokeclicker it would probably just have Jesse and James appear in places where they did in Yellow version or Let's Go Pikachu/Eevee. 
But hey, it shows the concept somewhat, so...

![Team Rocket Costume Meowth(1)](https://user-images.githubusercontent.com/114368571/193484633-67120dd0-aafc-4a83-8d6a-4488760a801e.png)

**Comment by Farboo171** [comment]
Several Jessie and James fights have been added since this suggestion, and they are always potential fodder for new quests and features. Closing, but specific ideas can be opened as new suggestions.
