### ISSUE TITLE
[SUGGESTION] Underground Diamond Rebalance

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#3176]
This suggestion will serve to rebalance the underground diamond gains in a manner that encourages digging over other methods of diamond gain, and provides enough diamonds via in-game information such that the Daily Chains discord command is no longer needed

**Current Behavior**
Doing 1000+ day chains in the underground using the discord bot is the only way to get enough diamonds to upgrade the diamond helpers

**Improved Behavior**
Change diamonds to be affected by achievement bonus and eliminate chains entirely

**Reason for change**
Balance and to encourage actual use of the underground after a certain point in gameplay

**Detailed Description**
For daily chains, the left side should consist of Diamond Items, Plates, and Fossils only. The right side should consist of shards and evo stones only. This division will still allow the player to either trade away Diamond Items, Plates or Fossils for their usual resource (Diamonds, gems, or hatches), or let them spend them in trades for other resources. This will completely eliminate chains as a way to get diamonds.

For the sale price of diamond items, I propose adding a multiplier the sale price. This multiplier would be:
1 + (Achievement Bonus)/100
Rounded down to the nearest integer FOR THE MULTIPLIER, not the sale price.
This would mean that for Achievement bonus 0%-99%, an Odd Keystone would sell for 6 diamonds, 100%-199% would sell for 12 diamonds, 200%-299% for 18 diamonds, and so on.

**Screenshots:**

**Comment by Claygame** [comment]
eliminating chains completely will not be good.
It will basically means that Underground is now only an endgame worth doing minigame, i think this will become the process that players will follow for doing underground: 
-> unlock it and mine layers only for the fossils as they have to do it to progress in regions, any further digging is waste.
-> it is a waste since they are too low on pokecoins to purchase restores since players will rather focus on proteins, balls, battle items etc
-> it will additionally feel a waste since if you do mine a few good items (Heart scale, keystone etc), players will hold on to them till very later regions so that they have some decent easy achieve% gain.
-> so it will be made so in the mind and playstyle of players that dont do underground until you are in kalos or alola otherwise you lose potential gain in diamonds.

This will basically make underground even more of an annoyance than what it already is.

**Comment by Jaaslet** [comment]
Or people will just use the underground normally during the game? Like selling stuff, when they can buy upgrades that helps them. Using it when they have time to spare. Stuff like that

**Comment by arduousFrivolity** [comment]
> It will basically means that Underground is now only an endgame worth doing minigame ... if you do mine a few good items (Heart scale, keystone etc), players will hold on to them till very later regions ... otherwise you lose potential gain in diamonds ...  basically make underground even more of an annoyance than what it already is

Currently the underground is a *not* worth doing minigame. You get your fossils, and then whatever else you get in the meantime you use in trades. If you mine **anything** you hold on to it until there's a daily deal that can increase it, otherwise you're losing out on potential diamond gain. The underground is currently an annoyance because in order to get enough diamonds to do literally anything from it, you have to go on the discord and use a bot command to tell you exactly what to trade for what on what day until you get the amount of diamonds you need. 

While I *am* iffy on removing diamond trades entirely, and possibly think the rounding should be to the sale price not the multiplier (ie; at 50% Odd Keystone would sell for 9 diamonds), a change definitely needs to be made, because you certainly should be able to get a comparable amount of diamonds by sitting down and grinding the underground today as you do by waiting 20 days to do a trade.

**Comment by RegisCoaxans** [comment]
**Regarding the deals :**
I believe that deals should be as free as possible, side-wise, but the users should not be able to trade for amount reasons, so deals have to destroy resources instead of creating more.
My idea is to increase the amounts required on the left side so trading only decreases the total amount of items that the users have. They would only trades if the item on the right matches their need more than the item on the left.
This solution does not need to put hard limitations on what is on the left or on the right, because chains would never result in the players stacking more and more items via trading anymore, but some deals would still definitely benefit to the players.
For instance, the left side could require 4-6 items instead of 1-3, and the right side would still provide 1-3 items.
Also, I do not like the idea that fossils do not appear on the right side anymore : they should be accessible from trades, especially when the pool of items to fill the layers still dilute in time the rates to find specific items.

**Regarding the increase is gain :**
I do not think that the value of the underground items should rely on the global progression through the game.
As the farm does, the underground has to mostly depends on the effort spent on playing that mini-game. Thus, the multiplier should be based on something related.
I could suggest *items found*, or *layers mined*, but I like *total diamonds* better. Why ? Because it means that the player has to sell items in order to get better prices. This best prevents the players from postponing their sells for better promises of benefits.
Of course, any of these statistics would make the sell prices increase exponentially so they have to be nerfed with `sqrt`-like or `log`-like functions.
As for example, I have made some calculations and ended up liking better log-like functions as they provide a good start but quickly squeeze so the multiplier does not madly increase.
Moreover, whatever the base for the multiplier is, the rounding should not apply on the multiplier but the final value, so players are not tempted to just stack items when they approach the next multiplier milestone, and the scaling feels smoother.

**Comment by Ultima1990** [comment]
Yes. Chains are bad. They encourage hoarding, they cause the player to never spend any diamonds on upgrades until they get that one big chain and then they buy it all at once. I imagine the goal is to have the player slowly acquire the upgrades slowly over time, instead of getting nothing for a long time and then suddenly everything at the end.

However, expecting the player to gain all of those upgrades by just digging is unreasonable. Currently a daily chain is pretty much required to make decent progress on those upgrades. Downside of that is, as outlined above, this results in players just getting everything all at once after one long chain. If chains are removed, there needs to be something to compensate for that. However...

As an ex-dev, I can also say with confidence that achieve% is a monstrous pile of radiating excrement. A nightmarish creature so disgusting that it makes even the braves of heroes violently gouge out their own eyeballs. And a balancing headache. Please, for the love of everything you care about, stay away from achieve%, don't stack any more effects on top of achieve%. Your future self will thank you.

Instead:
- Cap all daily deals. At, like, 10 or something. IDK. All numbers placeholder. Allow each deal to only be done X number of times per day. Keep daily deals the same otherwise.
- Add Treasure Hunter NPCs that will buy X number of Y underground item for Z massively increased diamond value, once per day. Allow treasure hunters to stack up these massively lucrative trades for like a week to prevent FOMO shenanigans where players feel forced to check in every single day. Have one treasure hunter per region, allowing access to more of these trades as the player progresses, resulting in a gradual increase of diamond gain.

With this players will be gaining a useful amount of diamonds every day, instead of nothing for months and then a massive load at the end. Most of this is gained from actually playing the digging minigame. Yes, there will still be hoarding, because you want to keep that X number of Y underground item in store in case that deal comes up, but not nearly as much hoarding as before because the player is constantly selling some.

So yea. That.

**Comment by Heppity** [comment]
I not sure your idea for "replacing Undergroun" would work out what you make it, as it would be even more FOMO then using achieve %.Kinda supirsed you didn't mention having a similar leveling system like with quest level as it would fit allow well with underground more than capping daily deals or have random Treasure Hunter which serves as pading.

**Comment by Ultima1990** [comment]
Achieve% has absolutely nothing to do with FOMO.

**Comment by Heppity** [comment]
> Achieve% has absolutely nothing to do with FOMO.

I was talking more about your Treasure Hunter idea not really Achieve% as that its own issue

**Comment by jk13pclick** [comment]
> * Cap all daily deals. At, like, 10 or something. IDK. All numbers placeholder. Allow each deal to only be done X number of times per day. Keep daily deals the same otherwise.

This was more or less the only part of #2096 that was completed. I scrapped the PR because of time constraints + getting frustrated trying to make the numbers not be hard capped, but scale upwards instead to make each deal "worse, but still doable" with more trades. That PR is worth looking at for anyone that wants to look at the Underground

**Comment by space244-hub** [comment]
Honestly i'd say the real issue with the underground is the fact that you can trade items for other types of items giving them theoretically infinite value. Personally i'd just combine both of ultima's ideas and cut out a lot of complexity.

Basically trades would only be for diamonds and each item would have a fixed value so the current values but everything without one would just sell for 1 diamond or however you want to balance it. Daily trades would instead be a multiplier for the base value so the more trades you have the more often you can sell your junk. You could then increase the multiplier with progress or make it a new upgrade option

**Comment by Farboo171** [comment]
Closed cuz there are better ideas than this and I'm not gonna do it.
