### ISSUE TITLE
[SUGGESTION] Alcremie EVs grind

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#3221]
**Current Behavior**
Currently Battle Cafe has a daily limit of 3 spins a day. It was discussed on discord that it would take months to have alcremie resistant with EV challenge off and years to fully make all 63 alcremie resistant to pokerus with the EV challenge on. 

It was also brought up that in the Sw/Sh games, you were only 1 spin a day.

**Improved Behavior**
Change the Battle Cafe to allow less of a grind for EVs after getting all alcremie forms.

**Reason for change**
Doing the change would make the grind to fully resist all alcremie forms less of a needed grind for those who want to fully resist all pokemon. #3173 is being worked on, but this would allow another way to gain EVs while still using the mini game created.

**Detailed Description**
Two options were presented.
1. Create a new achievement for getting all the alcremie forms. After achievement is triggered, the cap on spins per day can be removed or increased to a much higher number like 10.
2.  A quest line afterwards that would remove the limit or increase daily spin limit.

**Screenshots:**
N/A

**Comment by DorkyDelphox** [comment]
slight bit of misinfo here, in SwSh there's no daily spin/evo limit. The only limit tied to Alcremie is the 3 battle cafés are 1 battle a day each, so you have 3 chances to get one of the basic 5 sweets from a battle café daily (because they made ribbon and star sweets 'special' and only available from event-milcery raids) which you can also reset for iirc if they give you an unwanted item (they also offer regional snacks, exp candies, sachets and whipped dreams)

and to add to it; the achievement could be called Cake Boss, after the cake decoration/baking show :b

**Comment by Jaaslet** [comment]
I think the most fun solution would be to give an extra spin, each time you got all the forms from one berry.
And the plan is for this to be the only EV farming method for these, so yeah... We need to do something about the years of grinding for resistant
