### ISSUE TITLE
[SUGGESTION]: Increase Battle Frontier speed after certain milestones 

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#3472]
### Current Behavior

Currently Battle Frontier fight speeds are 2x when repeating previously beaten stages.

### Improved Behavior

Increase the fight speeds even more after reaching certain milestones like every 2k will increase the fight speed of previously beaten stages by an additional 0.5x or 1x.

### Reason for change

The time it takes for one sitting of the Battle Frontier is extremely long, its even worse if you used battle items and are unable to lower your attack even more to end the run. 

### Detailed Description

Attempting to do the Battle Frontier is a HUGE commitment of time invested in the game if you are attempting to climb the tower or even if you are attempting to attack the tower just for Battle Points. I feel an increase of attack speed beyond the current 2x would help with the dread of doing the Battle Frontier and give additional goals for people to aim for instead of just doing enough for the require Battle Points for whatever they are trying to purchase.

More context, my current Battle Frontier run is on stage 8500 (previous max of 9364) and it has been running for 10 hours and 40 mins. If I did not need the Battle Points to buy more key stones, I would not even bother with it due to how long it takes for me to complete a run. Sure I could use the check point system and go back to it, but total time required is still quite a lot and a much larger single commitment of time then any other feature in the game.

**Comment by RegisCoaxans** [comment]
I do not think that it will work.
The Battle Frontier obviously needs some improvements for long runs. But increasing the attack speed will not be — nor was — the proper solution :
- It has made the BF more powerful for grinding DPS than normal gameplay, way before lategame.
- It is a call for more and more speed increases and your suggestion just illustrates that.
- longterm-wise, it may cause more lags.

I have made some calculation with rough approximations and found out that, in a complete run, you go through about 40% of the stages with one attack per Pokémon, about the next 13% with two attacks per Pokémon, ... but only the last 4% of it with 10 attacks per Pokémon (thus, you need as many time as for the said 40% !!).

I had suggested some changes few months ago but my PR has got rejected.
Now, I would still rather ask for the checkpoints system to be improved so you are able to somehow skip parts of the run instead — either from the start or during the said run — instead of multiplying the speed in BF at all.

**Comment by xslk** [comment]
>It has made the BF more powerful for grinding DPS than normal gameplay, way before lategame.
It is a call for more and more speed increases and your suggestion just illustrates that.

A speed increase for only the Battle Frontier could still work. The high level required for the additional speed increase would rule out the benefit for majority of players until the grind for BP for any BP required items, most people tend to be under stage 1k.

> longterm-wise, it may cause more lags. 

There is almost no lag during BF runs.

I opened the suggestion and not a PR so that the discussion can be started on finding ways to make it less time consuming. There are not many people like me who are pushing such high Battle Frontier stages so any change might not benefit most players. Maybe a dev sees this and has an even better idea than anything we come up with.

**Comment by RegisCoaxans** [comment]
I know that it was a suggestion. That is why I have published my comment, participated to the discussion and shared my worries.

​឵
My point was as follows :

If the BF attack speed is increased, the breeding speed is increased as well, thus your damages will push you further, faster, and lead you to ask for more attack speed to compensate.
At stage 8000-10000, with +0.5 to the mutltiplier every 2000 stages, your attack speed is 4 times the initial speed, twice as fast as the current speed, thus your hatchery will be twice as efficient as the BF makes it now. At the same stage, with +1 to the multiplier instead of 0.5, your attack speed is 6 times the initial speed, you will gain power three times as fast...

In your case, in early September, you were at stage around 6500, now, you are 3K above that. Which stage will you reach three months later with a hatchery two or three time as powerful ? Will the increase in speed still be enough ?
If you manage to reach 14000 stages — I think that you might do better, lol —, you will still do a run in a grand total of ten hours and will go back to stupidly high times in half a year.

​឵
Therefore, I do not think that any speed increase is a solution at all. I even think that the current speed increase should be replaced.
My best guess is that checkpoints can be improved and serve your cause; and I ask for your opinion on how they should work and make BF feel less like a waste of time.
Being able to start the BF run at a higher stage ? Being able to skip stages during the run ? Being able to get BP at certain milestones ? I can not think of other options, but you may !

**Comment by jk13pclick** [comment]
We do not want to increase the speed in the BF as it will likely exacerbate existing lag issues. However, we would like to improve our checkpoint system and allow people to start further in the BF if they have reached certain milestones. This would likely come with some kind of reduction in BP earned from such runs. Therefore, the implementation described in this issue is rejected, but an implementation more aligned with the outline in this comment is approved.

**Comment by xslk** [comment]
After careful consideration and mathing, additional speed to the BF does not work. Something else will need to be done instead
