### ISSUE TITLE
[SUGGESTION]: Add other Vivillons to lunar new years event

### ISSUE THREAD

**Issue by xslk** [pokeclicker/pokeclicker#3480]
### Current Behavior

After you complete the vivillion questline they disappear forever like they are extinct

### Improved Behavior

Adds the rest of the Vivillons to the lunar new years event

### Reason for change

More pokemon to EV, gives the event a little more than just fancy Vivillon, could even rename the event to spring festival or something more in line with the event

### Detailed Description

My plan is to add the other Vivillons back to the dungeons they are caught in during the questline as rather a dungeon boss again or a legendary mimic with 2x weight during the lunar new years event. 

I have not thought of a good place for pokeball vivillon yet didn't want to come up with that one yet if this suggestion is rejected.

**Comment by RedSparr0w** [comment]
Maybe just add the Requirement that they need to be caught already to the event spawns too.

**Comment by xslk** [comment]
> Maybe just add the Requirement that they need to be caught already to the event spawns too.

Yup. I totally spaced and forgot to add that the requirement would be completion of the quest line for them to spawn again

**Comment by osherwott** [comment]
I would love for more Vivillon's patterns to be available in the wild! If I may recommend, how about limiting it to only the patterns that correspond to the real-world equivalent countries that celebrate Lunar New Year? It would prevent the roaming chances from being too crowded with too many pokemon while celebrating the real world nations!
And if you'd like to have them all EV trainable, how about the Friend Safari? I see potential now that regional safari zones are easier to code! There could be a timed rotation from a random pool for all the patterns to keep each visit fresh! Poke Ball pattern could even be coded to be extra rare!

**Comment by xslk** [comment]
> how about limiting it to only the patterns that correspond to the real-world equivalent countries that celebrate Lunar New Year? 

I don't quite understand this

> And if you'd like to have them all EV trainable, how about the Friend Safari? I see potential now that regional safari zones are easier to code! There could be a timed rotation from a random pool for all the patterns to keep each visit fresh! Poke Ball pattern could even be coded to be extra rare!

Most people find safari zone to be the worst part of the game so I'm pretty sure you won't have many fans for this. I believe the framework for multiple safari zones is also setting up for the bug catching contest stuff.

**Comment by osherwott** [comment]
> I don't quite understand this

Vivillon's patterns correspond to real-world regions! Adding patterns that are assigned to such regions that celebrate Lunar New Year, like Continental, High Plains, Monsoon, Jungle, and Elegant would be a rather charming detail!

> Most people find safari zone to be the worst part of the game so I'm pretty sure you won't have many fans for this. I believe the framework for multiple safari zones is also setting up for the bug catching contest stuff.

If a regular safari is unavailable, then perhaps something more along the lines of a dungeon? I am afraid I am not too keen with ideas. Vivillon is a unique pokemon however, and I implore you to consider utilizing it as such!

**Comment by CypherX** [comment]
> Vivillon's patterns correspond to real-world regions! Adding patterns that are assigned to such regions that celebrate Lunar New Year, like Continental, High Plains, Monsoon, Jungle, and Elegant would be a rather charming detail!

This PR is about adding the existing Vivillons found only during the Vivillon Hunt quest line to their respective dungeons as bosses and/or mimics during the Lunar New Year event, not adding new Vivillon forms.

**Comment by xslk** [comment]
> Vivillon's patterns correspond to real-world regions! Adding patterns that are assigned to such regions that celebrate Lunar New Year, like Continental, High Plains, Monsoon, Jungle, and Elegant would be a rather charming detail!

That makes much more sense, I still don't like that then event is called a lunar new year event just because it has almost nothing to do with lunar new year other than the days. Butterflys tend to signal the start of spring, hence the suggestion to change the name to spring festival since a summer festival exist in the pokemon world. 

> If a regular safari is unavailable, then perhaps something more along the lines of a dungeon? I am afraid I am not too keen with ideas. Vivillon is a unique pokemon however, and I implore you to consider utilizing it as such!

The original suggestion is 
**1.** Dungeon boss reappearance during the event after the questline is complete 
**2.** Dungeon mimics during the event after the questline is completed.

**Comment by osherwott** [comment]
> This PR is about adding the existing Vivillons found only during the Vivillon Hunt quest line to their respective dungeons as bosses and/or mimics during the Lunar New Year event, not adding new Vivillon forms.

You are right and I apologize, I missed that part! Thank you for clarifying.

> Butterflys tend to signal the start of spring, hence the suggestion to change the name to spring festival since a summer festival exist in the pokemon world.

Yes, I agree. That would be better for posterity if any expansions for the event should arise.

> The original suggestion is **1.** Dungeon boss reappearance during the event after the questline is complete **2.** Dungeon mimics during the event after the questline is completed.

It is a smart idea to have them reappear during the event to solidify the thematic of a butterfly migration, indeed. I apologize if my earlier comment came off as brash. I would still rather give them a proper "home" so to speak, but I have nothing yet to offer. Should I have any further ideas of a year-round implementation, I will comment on this issue. In the meanwhile, pardon my intrusion.

**Comment by osherwott** [comment]
I believe I have an idea for its inclusion in the friend safari. Please let me know if this would be something worth creating a new suggestion for.

Like in the games, the safari will be split up into further subdivisions by type and have an encounter style similar to routes: one pokemon after the other. You pay gems of a type to enter that safari's type. The gems of that type will keep being used up once inside, much like flutes, only costlier. You will be free to exit whenever, since the only time limit will be the amount of gems you have. It is in the Bug safari where you will be able to EV train Vivillon.

I imagine it having a daily rotation much like Unown in the Ruins of Alph, but without a preview since it would not be a traditional dungeon, encouraging/forcing the player to interact with the safari. This rotation will only be unlocked after the completion of the Great Vivillon Hunt quest. To keep each typed safari varied, I assumed all pokemon from all slots of the games would be included, giving most pokemon a 1/12 chance of appearing. I believe that this, along with the added cost of gems, should be challenging enough, yet feasible to EV train pokemon in. If difficulty adjustments are needed, there is always the matter of whether the player can use their own balls or safari balls, or having an npc report the daily pattern or a weekly prediction of 7 at a time.

The safari can also feature other non EV-trainable pokemon forms like Sawsbuck and Floette, which are much fewer than Vivillon's and wouldn't need a rotation of their own. And for its purpose, the goal of the Friend Safari would be to have the longest catch streak possible, rewarding anything from berries that correspond to that type or the eventually-implemented contest points.

And best of all, you wouldn't have to rename the Lunar New Year's event! Also, a correction to my earlier list: it seems the celebration is not part of modern Japanese culture, so the inclusion of Elegant wouldn't make much sense. Sorry for misinforming you! I suppose what you make of the event doesn't matter much, but I'm such a fan of cultural variety and I see Lunar New Year's as a welcome addition to the other events!

**Comment by xslk** [comment]
I believe a new suggestion would be better. Friend safari itself deserves its own suggestion to be discussed and not lost in this suggestion.

**Comment by osherwott** [comment]
Do you think it would work well for Vivillon forms?

**Comment by jk13pclick** [comment]
This idea is approved! I think adding them back as Dungeon Bosses makes the most sense.

Also, feedback on #3490 as an adjacent mechanic is forthcoming.
