### ISSUE TITLE
Add Eviolite to the Game

### ISSUE THREAD

**Issue by WizardSpriter** [pokeclicker/pokeclicker#3520]
### Current Behavior

Currently, the game has several items that can be given to specific pokemon to increase their attack. However, the eviolite is not among them.

### Improved Behavior

I think it would be interesting to see the eviolite to the game. 

### Reason for change

It would allow for some pokemon with worse breeding efficiency to reach higher attack. Some examples of pokemon that could benefit from this are Chansey, Diglett, Alolan Diglett, Wimpod, and Spewpa. All of these pokemon have incredibly low breeding efficiency despite their low base attack and would all benefit from an item like the eviolite.

### Detailed Description

The eviolite could be obtained in several ways, since it's been in the main series games for a while. 
Some ideas are: 
Dream Orb Reward
Gift in Ballonlea
Reward from Battle Frontier (would be a reward multiple times)
Underground
Berry Master Trades

It would probably boost a pokemon's attack by 1.5% or somewhere along those lines.

**Comment by Jaaslet** [comment]
So you just want us to add a 10x as strong version of an item that already exists?

**Comment by osherwott** [comment]
Perhaps it could make the Real Evolutions challenge more interesting, but I agree with Jaaslet that it'd be best for balancing if it wasn't available normally.

**Comment by WizardSpriter** [comment]
It wouldn't increase attack per breeding cycle, it would just increase the attack of the pokemon currently.

**Comment by jk13pclick** [comment]
Rejected as described. Eviolite should boost defensive stats (which are factored into the Base Attack statistic), or an analogous mechanic if anything. Boosting raw defensive stats has yet to be done AFAIK because base attack is calculated on load in PokemonList, but if it can be done this is approved. Going to close this issue, feel free to reopen if desired with changes as per the described suggestions.
