### ISSUE TITLE
[SUGGESTION]: Monotype Challenge

### ISSUE THREAD

**Issue by Crobat4** [pokeclicker/pokeclicker#3727]
### Current Behavior

No proper monotype challenge.

### Improved Behavior

Add a monotype challenge compatible with other challenges, catching-related quests, etc.

### Reason for change

Just a challenge for those who decided to go with a self imposed monotype challenge and want the game to ignore Pidgey's damage.

### Detailed Description

Just suggesting a proper monotype challenge that lets you select a type and only Pokémon that contains the said type are able to attack, similar to how Magikarp Jump subregion works. If it gets approved, I can provide a PR about this.

The changes I made were to try to tackle all possible softlocks that can occur depending on the selected type.

Changes compared to a normal run:
* Only Pokémon that contains the selected type can deal damage.
* Badge level cap removed to being able to use the hatchery to avoid any damage-related softlocks.
* Hatchery unlocked after completing Viridian Forest to avoid Electric monotype softlock on Brock.
* Quests unlocked after completing Viridian Forest to being able to purchase Mystery Eggs.
* Town Map unlocked after catching the starter to avoid Pidgey softlock in Ground monotype.
* Added a Safari-esque feature in every starting town that increase egg steps to avoid hatchery softlock if all Pokémon that can deal damage are in there (assuming no click attack challenge).
* Kanto original starters are replaced by a single starter depending on the selected type.

Other features/restrictions:
* Dark-type can't be selected.
* Challenge can't be disabled until the player gets the Earth Badge to avoid any possible unintended behavior regarding Badge level cap removal and hatchery unlocking earlier.
* Party list shows all Pokémon that can deal damage on the top of the list and the ones who can't are greyed out (This also applies in Magikarp Jump).
* On older saves, the monotype starter is given if the challenge is enabled.
* Starter can't be skipped anymore (Can be restricted to Monotype challenge if other self imposed challenges needs the skip but this was made to avoid another softlock).

Some screenshots:
<details><summary>Pics</summary>

![image](https://user-images.githubusercontent.com/104547700/211128800-b76e7aa8-641a-4aed-972f-2e28b13a1b09.png)
![image](https://user-images.githubusercontent.com/104547700/211128822-62e45a69-cdc8-4d9c-a39f-37319c301243.png)
![image](https://user-images.githubusercontent.com/104547700/211128943-f17b5676-cccf-4155-9960-125262dacbf9.png)
![image](https://user-images.githubusercontent.com/104547700/211128909-6619f45c-ea73-4d86-8e04-af3fa5ed4c7d.png)
![image](https://user-images.githubusercontent.com/104547700/211129154-31ba471e-a3d2-402c-ad0a-682b06ba0ad3.png)
![image](https://user-images.githubusercontent.com/104547700/211129162-5e5f9b6b-3c34-4d9a-84be-6036f3fb13e1.png)
Yeah, I know is empty...
</details>

**Comment by xslk** [comment]
> Only Pokémon that contains the selected type can deal damage.

Will dual typed pokemon will still do both types of damage?

> Badge level cap removed to being able to use the hatchery to avoid any damage-related softlocks.
Hatchery unlocked after completing Viridian Forest to avoid Electric monotype softlock on Brock.

Removing badge level caps would already take care of the issue of getting stuck on brock, assuming dual types will still do damage. With level cap, shiny coding in a magneton and surfchu already get you past brock, adding flying chu and its overkill. 
I believe removing the level cap will not stop you from being damage walled anywhere before the hatchery.

> Town Map unlocked after catching the starter to avoid Pidgey softlock in Ground monotype.

Assuming the starter is sandshrew, using the shiny code on the geodude line solves this issue. 

There is also a handful of people always theorycrafting about monotype challenges on the discord challenge runs channel if you want even further input or discussion on this.

**Comment by xslk** [comment]
> Only Pokémon that contains the selected type can deal damage.

Will dual typed pokemon will still do both types of damage?

> Badge level cap removed to being able to use the hatchery to avoid any damage-related softlocks.
Hatchery unlocked after completing Viridian Forest to avoid Electric monotype softlock on Brock.

Removing badge level caps would already take care of the issue of getting stuck on brock, assuming dual types will still do damage. With level cap, shiny coding in a magneton and surfchu already get you past brock, adding flying chu and its overkill. 
I believe removing the level cap will not stop you from being damage walled anywhere before the hatchery.

> Town Map unlocked after catching the starter to avoid Pidgey softlock in Ground monotype.

Assuming the starter is sandshrew, using the shiny code on the geodude line solves this issue. 

There is also a handful of people always theory crafting about monotype challenges on the discord challenge runs channel if you want even further input or discussion on this. We would love to have you there to explore this feature more deeply.

**Comment by CypherX** [comment]
What if rather than implementing monotype as a 'challenge' it gets put into a separate category of game-altering settings, perhaps call it a 'restriction' instead? That way it doesn't impede AC folks and solves issues monotype runs currently have with not being able to complete certain quests, participating in BF, and so on.

**Comment by xslk** [comment]
@arduousFrivolity had a concept they were working on to separate it away from being a challenge mode and make it an entirely different category

**Comment by Crobat4** [comment]
> Will dual typed pokemon will still do both types of damage?

Yes.

> Removing badge level caps would already take care of the issue of getting stuck on brock, assuming dual types will still do damage. With level cap, shiny coding in a magneton and surfchu already get you past brock, adding flying chu and its overkill.
I believe removing the level cap will not stop you from being damage walled anywhere before the hatchery.

Wasn't talking about Brock himself but about any impossible damage wall any monotype could find in the game since if the Pokémon is not lv100, they can't use the hatchery to increase their attack, but if it's not needed and Mystery/Typed eggs are enough for the damage increase, it can be taken out of this.

The Brock problem with Electric monotype was the immunity, that's why the hatchery before Brock, so you can get Magnemite for him, Honestly, I forgot about the shiny code but IMO codes and event Pokémon shouldn't be taken in account for stuff like this since codes are either hidden outside the game or time gated? (Surfing Pikachu) and events are yearly.

> Assuming the starter is sandshrew, using the shiny code on the geodude line solves this issue.

Same as before, forgot about the code.

---
> We want to help support monotype, but it will never be an official challenge.
We don't want challenges that are too hard, because AC players won't be able to ignore it, and will be annoyed.

Fair enough.
I like CypherX and Arduous ideas of separate the normal challenges and special challenges so it doesn't bother AC people and helps monotype people, but if it's not wanted this way neither, I understand.

**Comment by Jaaslet** [comment]
> I like CypherX and Arduous ideas of separate the normal challenges and special challenges so it doesn't bother AC people and helps monotype people, but if it's not wanted this way neither, I understand.

I tried to implement shiny dex at some point, and add it as "impossible challenge" or something. Got a lot of pushback

**Comment by arduousFrivolity** [comment]
This is something I have put a decent amount of thought and time into. 

The general flow I imagined was: If you select monotype challenge, it changes Professor Oak's dialog at the beginning of the game. Instead of offering you a pokemon, he offers you a list of types; choosing the type initiates battle with a pokemon of that given type. 

For DT, the idea would be to put the chosen starter pokemon on Route 22. This would suck for monotypes that don't have another source of DT until way later, but thems the breaks. For later regions, there would be two options to prevent a softlock from leaving while not having the DT to get to the dock; either put the starter on a route prior to the first dungeon in that region as well, or just have docks unlocked right away in monotype. 

The tutorial can be maintained if wanted by making Catch 5 pidgey into Catch 5 [starter].

As for the classification, my idea was to make it separate from regular challenges but basically the same under the hood. Call it "Game Modes" or "Special Challenges" or anything to indicate that it is not the same as a regular challenge, and have the category be for things that vastly change the balance or flow of the game, or are mutually exclusive with other challenges (For example, Monotype would be mutually exclusive with Require Pokedex). It would be my hope that having this be a separate category would be enough to let AC players know that we intend these to not be included in AC runs. (Mockup at bottom). 

> Badge level cap removed to being able to use the hatchery to avoid any damage-related softlocks.

I found by fooling around a little that you can actually set the hatchery level requirement to the badge level requirement; so that when you beat Brock you can breed pokemon at level 30, but only level them to 30. I thought that was a fun workaround to both allow breeding early but without letting you level to 100 on route 1. The other option I considered for damage was 'monotype eggs', an egg that would hatch a pokemon based on your chosen monotype. Adding both would let players choose their damage source; some feel like hatching the eggs until Giovanni is a part of the challenge, some would be happy to bypass it entirely. 

Other considerations are ways to avoid being required to interact with other types; Quests that require you to catch a type other than your monotype could be removed, wanderers could be opt in so you can access the farm, and quests that require you to catch a pokemon to complete could either be altered to defeat the pokemon when the challenge is active, or allowed to be skipped. 

The last major thing I considered was pokemon that you are unable to obtain due to requiring a type outside your monotype to evolve, such as a flying monotype requiring a caterpie to get a butterfree, and the inverse (a pokemon losing it's type upon evolution). The latter would need handling, and it would be cool if the former could have alternate methods to obtain as well. I have compiled most of this info in a spreadsheet, which hopefully is helpful: https://docs.google.com/spreadsheets/d/1kGUhsmwx6XgYKcBQrPLFUV7FkbSdWkHskp4rrMRws18/edit?usp=sharing

A lot more of my thoughts are collected a lot more coherently on the discord, searching `from: arduousFrivolity#5924 in: challenge-runs` has a lot of my thoughts, though unfortunately I believe code snippets were lost with the old dev help channel.

![MonotypeMockup](https://user-images.githubusercontent.com/112739771/211219441-a2cf860c-d7c7-4b88-9467-ee859878fde5.png)

This likely isn't all inclusive of my thoughts, and I may try to organize a bit better later. I would love to see this idea come to light though!

**Comment by Crobat4** [comment]
> For DT, the idea would be to put the chosen starter pokemon on Route 22. This would suck for monotypes that don't have another source of DT until way later, but thems the breaks. For later regions, there would be two options to prevent a softlock from leaving while not having the DT to get to the dock; either put the starter on a route prior to the first dungeon in that region as well, or just have docks unlocked right away in monotype.

What I did was so you can catch anything and just limiting the damage of non-selected type Pokémon, but something like disable DT gain for those Pokémon and adding the starter before the first dungeon of each region sounds more fitting for this, I think, plus it would still be compatible with the Pokédex completion challenge.

> As for the classification, my idea was to make it separate from regular challenges but basically the same under the hood. Call it "Game Modes" or "Special Challenges" or anything to indicate that it is not the same as a regular challenge, and have the category be for things that vastly change the balance or flow of the game, or are mutually exclusive with other challenges (For example, Monotype would be mutually exclusive with Require Pokedex). It would be my hope that having this be a separate category would be enough to let AC players know that we intend these to not be included in AC runs. (Mockup at bottom).

This would be good, but according to Jaaslet's previous comment, even as a separated category, it wasn't well received in the past.
If it's the same with this, I guess a challenge like this is not possible.

> I found by fooling around a little that you can actually set the hatchery level requirement to the badge level requirement; so that when you beat Brock you can breed pokemon at level 30, but only level them to 30. I thought that was a fun workaround to both allow breeding early but without letting you level to 100 on route 1. The other option I considered for damage was 'monotype eggs', an egg that would hatch a pokemon based on your chosen monotype. Adding both would let players choose their damage source; some feel like hatching the eggs until Giovanni is a part of the challenge, some would be happy to bypass it entirely.

Yeah, these options sound better to be honest.

> Other considerations are ways to avoid being required to interact with other types; Quests that require you to catch a type other than your monotype could be removed, wanderers could be opt in so you can access the farm, and quests that require you to catch a pokemon to complete could either be altered to defeat the pokemon when the challenge is active, or allowed to be skipped.

Didn't check the quest code but I guess rerolling a capture <type> Pokémon quest or making it so you need to capture the selected type while the challenge is active would be doable.

For wanderers, I think an option could be, if the challenge is enabled, make Pamtre purchasable and remove wanderers from it if possible, so you can mutate Micle (for the repel aura) without getting a wanderer of the type you didn't select during the mutation, and then re-enable them once you get a Micle (or the four? needed for 100% repel), I don't know if this could be abusable in any way though.
Or just make Micle purchasable after certain conditions.

> The last major thing I considered was pokemon that you are unable to obtain due to requiring a type outside your monotype to evolve, such as a flying monotype requiring a caterpie to get a butterfree, and the inverse (a pokemon losing it's type upon evolution). The latter would need handling, and it would be cool if the former could have alternate methods to obtain as well.

I think leveling/evo stoning non-selected type Pokémon to get the Pokémon you wish is fine, but if is not wanted, maybe they can be added in dungeons/routes/shops as you said, maybe even eggs in some cases, Dragon egg already has evolved forms in the pool so I don't think it would be a problem (aside bloating the pools).
As for the ones losing the type, I think it would be the best if Everstone was a held item, but it would need an item code rework since it's already a diamond item.

---
> I tried to implement shiny dex at some point, and add it as "impossible challenge" or something. Got a lot of pushback

That's unfortunate.
Do you think it will be the same with this? If so, I can close this and suggest instead a setting where you can select a type and it does the damage thing I made for this challenge, maybe the quest rerolling I mentioned before too if possible.

**Comment by Aegyo** [comment]
This is approved :+1: 

Some notes:
- Hatchery available at badge cap sounds good
- The tutorial could be skipped entirely if this challenge is active (QP awarded for free)
- Spooky Bulbasaur could be used for a Dark starter

**Comment by Farboo171** [comment]
Closing, as detailed in #4086
