### ISSUE TITLE
[SUGGESTION]:  capture buff in dungeon 

### ISSUE THREAD

**Issue by Belsaadi** [pokeclicker/pokeclicker#3794]
### Current Behavior

as far as i know there is nothing about this

### Improved Behavior

add a 10% boost to the catch rate of the boss pokemon on 100% completion

### Reason for change

Some pokemon (like legendaries) are very elusive especially when you dont have masterballs. It would give more incentive to do all the fights as well.

### Detailed Description

When you complete a dungeon (all fights and all items) add a small bonus to the capture rate of the boss pokemon.

**Comment by Aegyo** [comment]
There is the dusk ball which gives a 15% bonus in dungeons

**Comment by renardor** [comment]
In theory, yes, dusk ball gives a nice bonus. But in reality, you can't really use dusk balls for the whole dungeon, because these balls are too rare. If you want to use them for the boss (once you've already captured it), you have to stop, go to your ball settings, change the ball, and then attempt it. It's quite tedious, imo.
Dusk balls are great for new pokemon since you have two different settings.

**Comment by Aegyo** [comment]
I was mentioning dusk balls because you said "as far as i know there is nothing about this". Just clarifying the current situation, not rejecting your suggestion.

There are hotkeys for selecting pokeball settings making it less tedious, and there will probably be options in the future for a setting to only catch dungeon bosses (#1712)

Also your detailed description only mentions adding a bonus to the boss pokemon, not the whole dungeon.

**Comment by Aegyo** [comment]
Discussed with other devs and decided that an extra capture buff isn't wanted, and catch filters + making dusk balls easier to get should be done instead.

Ideas for making dusk balls (and others) easier to get should be in a separate suggestion though.
