### ISSUE TITLE
[Bug]: Vivillon replacing Parasect in manaphy questline

### ISSUE THREAD

**Issue by UlysseGuyon** [pokeclicker/pokeclicker#3877]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

During the manaphy questline in Sinnoh, when we are asked to fight a parasect in the Eterna Forest, there are two bosses available : parasect and vivillon. I completed the dungeon by fighting the vivillon boss and that completed the quest.

### What did you expect to happen?

I expected either to not be able to fight a vivillon during this quest or that the quest wouldn't complete as long as I didn't fight the parasect boss in Eterna Forest

### Steps to Reproduce

1. Use a save that has the vivillon questline completed
2. Do the manaphy questline during the Lunar New Year Event
3. During the quest that ask to fight the parasect boss in Eterna Forest, You should be able to see 2 bosses in the preview : parasect and vivillon
4. Complete the Eterna Forest dungeon by fighting only the vivillon boss
5. The quest completes but shouldn't

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Firefox

**Comment by Leafsw0rd** [comment]
Investigated this: 
This is because of an oversight. The Vivillon Event and the Manaphy quest were coded at two very different times (...albeit both by me), and the vivillons were mostly added through an algorithm using pre-set values. A special case has been made so that River Vivillon, the one who spawns in Eterna Forest, now has both the standard Vivillon event requirement and the same conditions that make the normal eterna bosses despawn. In function, like the othher bosses, Vivillon will now disappear from the boss roster and return after the Parasect clear. 

It should still be possible to trigger the Quest version of Vivillon during the Parasect quest step, but that would require much more deliberate attempts to provoke this error, whereas this merely required doing the update and having River Vivillon already.

**Comment by Qwertypop04** [comment]
Fixed as of #3842, closing
