### ISSUE TITLE
[SUGGESTION]: Speed up Battle Frontier

### ISSUE THREAD

**Issue by Elefunt** [pokeclicker/pokeclicker#3950]
### Current Behavior

Unable to click attack in battle frontier which means once you get to the higher levels it takes a LONG time to get through each session.

### Improved Behavior

Enable clicking but instead of it being your click attack damage it will do you standard pokemon attack damage and reduce the timer by one second.
This will mean you still can only get to the same point in battle frontier but you will be able to do it more actively and quickly if you are not AFK.

### Reason for change

At the moment battle frontier is only AFK and takes a long time. Its very time gated as most people can only do one maybe 2 a day at end game depending on how much they play

### Detailed Description

Enable clicking in battle frontier but instead of it being your click attack damage it will do you standard Pokémon attack damage and reduce the timer by one second.

This will mean you still can only get to the same point in battle frontier, but you will be able to do it more actively and quickly if you are not AFK.

**Comment by Razorflamekun** [comment]
Click attack is purposefully disabled in the Battle Frontier.  Your suggestion would be incredibly unbalanced is it would allow someone with any amount of clicking ability to be able to go through a BF run in like 10-15 minutes, and still get the full reward.

Battle Frontier is purposefully meant to be slow as well as AFK because it is meant to test your Pokemon's abilities.  There is never any amount of input from the trainer because of this factor.

If you find BF slow at the moment, that's all right as there are many people that find it slow at the moment, and there are people working on finding ways to improve the Battle Frontier.

I've already suggested an auto-start button for the Battle Frontier, which was accepted, because it has both an upside and a downside, as it would allow you to automate the Battle Frontier, but at the cost of some of the Battle Points you get during the run.

Please remember that game balance is always an important factor in whether or not a suggestion would be accepted.

**Comment by Elefunt** [comment]
Hi Razor,

I thought about that afterwards and you are right it would make getting the tokens to quick. I also saw your suggestions and think its a great idea
