### ISSUE TITLE
[Bug]: Egg stuck in the hatchery

### ISSUE THREAD

**Issue by grianola** [pokeclicker/pokeclicker#4177]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

A grass egg is stuck in the hatchery,
he restart every time he finishe growing
i don t know how to make it go away

### What did you expect to happen?

![image](https://user-images.githubusercontent.com/131445876/233598103-01753bfe-6677-4e9d-9b6f-b2fb4d29a573.png)

### Steps to Reproduce

i think it was an egg i bougth 

### What operating system are you using?

Windows 10

### What browsers are you seeing the problem on?

Opera

### Additional Information

thanks !

**Comment by LuchoDreamer** [comment]
You are using a helper, helpers take eggs automatically from your list of available pokemon to breed. I'm guessing it's on default, so it's doing it by ID. So it's doing Bulbasaur, then Ivysaur, then Venusaur. Since Sam is a pretty bad helper, Bulbasaur is back to lvl 100 when Venusaur is finished breeding, so it restarts.

Either fire the helper, or change the filter on what the helper breeds.
