### ISSUE TITLE
Be able to choose lapras

### ISSUE THREAD

**Issue by Amasingearth** [pokeclicker/pokeclicker#4424]
### Current Behavior

Currently, the game forces you to get a lapras right after you beat Blue in Silph. CO.

### Improved Behavior

I would like to see the ability to choose whether or not you want a lapras by making an npc give it to you, instead of it just being given to you by blue

### Reason for change

This is an improvement because this would allow many mono-type runs to be possible, as well as a new min-catch run to be done

### Detailed Description

For this to be possible, there would be a new npc, Silph Employee, available to talk to in Silph CO. Before you beat Blue, they would say, “You don’t look strong enough yet. Come back when you are stronger so I can give you this lapras.” When you beat Blue, but before you claim the lapras, they would say, “You have proven worthy for this lapras. Here you go!” Once you claim the lapras, they would say, “I don’t have anything for you anymore. I hope you continue to do good!”

**Comment by Amasingearth** [comment]
Not only this, but

**Comment by LuchoDreamer** [comment]
Yeah, this is one idea I think we all have. But we have no way in the code yet to make NPCs give gifts. Once that is introduced, this is probably one of the first things that it will be done.

Keep in mind though that pidgey is still forced because of the tutorial. And that without Lapras, many monotypes challenges are not actually beatable, since you cannot beat Brock, which is what unlocks the hatchery. (People use the shiny code to get Lapras to beat Brock since Lapras is mandatory later on anyway)

**Comment by Amasingearth** [comment]
Not only this, but there are many other ways of getting Lapras in Kanto, such as water eggs or just routes/dungeons in general

**Comment by Farboo171** [comment]
#4586 resolves this
