### ISSUE TITLE
Replay value of Safari Zone

### ISSUE THREAD

**Issue by elitepokefans** [pokeclicker/pokeclicker#466]
In my opinion currently the replay value of Safari Zone is pretty low once a player managed to catch all the available pokemon inside.  There is not much incentive for players to re-enter except maybe trying to encounter wild shiny inside.  I understand that the issue of charging entry fee has been brought up earlier, even if free of charge I still prefer other activities than going back inside.

Suggested it could be like the other items that can be level up through usage.  Once a player managed to catch all available ones the zone level up too.  A possible incentive can be an increase chance of wild shiny encounter inside.

**Comment by danfroese** [comment]
Is the issue that the Safari Zone is too bland and boring to replay, or that it doesn't offer enough rewards so that you feel pressured to do something more productive? Fixing bland content by forcing people to play it isn't good for the long-term health of the game. But if it's fun but with too little reward, then making a daily quest could be the right solution.

Personally, I find the Safari Zone to be an active part of a game that I am playing because I can passively play it. I did as little of it as I could get away with. I don't want to have to spend significant time in there. But a short daily jaunt into the safari zone, similar to the Underground might be nice. The Underground rewards you with shards and has a unique upgrade system built into it, though. Maybe something like that in the Safari Zone?

Give increased shards for the types of pokemon you capture, and rewards for every 5-10 of a particular pokemon you catch, with upgrades you can buy (# of safari balls, # of pokemon needed for rewards, ball/rock/bait effectiveness).

You could also consider having a random daily selection of pokemon available in the safari-zone, probably locked behind completing the Kanto-dex?

**Comment by jk13pclick** [comment]
Closing this. While improving the Safari Zone is certainly important to us, this discussion issue is a bit outdated and stale. We have already implemented berry throwing - other uses of the Safari Zone (EVs for example) are being worked on.
