### ISSUE TITLE
[BUG] Selecting MAX when buying key items freezes the game

### ISSUE THREAD

**Issue by fujnw** [pokeclicker/pokeclicker#477]
**Steps to Reproduce:**

1. Go to Pewter City shop
2. Select Dungeon Ticket
3. Click Max
4. Game freezes

**Expected Behavior:**
Max on a key item should not do anything, as only one can be bought.

**Comment by RedSparr0w** [comment]
Caused by the following code:
https://github.com/pokeclicker/pokeclicker/blob/c8aae81b22309f257adea8d71fd5345900b4b5b3/src/scripts/items/buyKeyItem.ts#L12-L14

It is always using returning the base price, so if you have more than the base cost, it will infinitely run.

If this is removed, then the price would change in the shop to look as though you can buy more:
![image](https://user-images.githubusercontent.com/7288322/71760527-f50f4180-2f23-11ea-9316-bf773c975562.png)
