### ISSUE TITLE
[SUGGESTION]: Downloads for mobile users

### ISSUE THREAD

**Issue by GamingG0D10101256** [pokeclicker/pokeclicker#4806]
### Current Behavior

It only has computer downloads

### Improved Behavior

I just want mobile users to be able to download it too

### Reason for change

It is hard to see the game on google making it easier access and more visibility on mobile

### Detailed Description

Just a download button or option for mobile players

**Comment by RealPendragon** [comment]
This is not as easy and simple as you think.

**Comment by Symi001** [comment]
More than not being easy or simple, it'd mean making an apk and never putting it on any store because of copyright reasons. It would also open a can of worms, as ppl would more easily make their own apk and make your pay for it, which in turns would mean the death of the project in the longer term.
What you are asking is simply impossible, I'm afraid.

**Comment by osherwott** [comment]
Very well-worded, Symi. Mobile downloads are not a simple feat.
Sorry to disappoint, but unfortunately this is something we simply cannot do.
