### ISSUE TITLE
[Bug]: Some quest trainers do not appear

### ISSUE THREAD

**Issue by ver1nty** [pokeclicker/pokeclicker#4833]
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

In some quests, trainers or the button to battle them do not appear:

**Theam Rocket's Pinkan Theme Park**
After defeating Pinkan Jesse and James in step 6, Pinkan Officer Jenny does not appear in Pinkan Pokémon Reserve (no button appear for battle).

**Delta Episode**
When a Aqua Grunt and Magma Grunt should appear in Mossdeep Space Center, only the Aqua Grunt appears there.

**An Unrivaled Power**
At the step 'It flew off to a faraway region to hide in a large city. Defeat Anomaly Mewtwo yet again.' the Mewtwo icon does not appear in Unova map.

**Sword and Shield**
At the step 'Hop wants to fight you one more time at Slumbering Weald Shrine' the button for battling Hop does not appear.

### What did you expect to happen?

Trainers appear when that part of the quest is reached.

### Steps to Reproduce

Just follow the quest.
Not sure if issue is related to v0.10.16 (running the game locally), nor if the issue is affecting all the quests flow.

### What operating system are you using?

Windows 11

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by Qwertypop04** [comment]
Need a screenshot of Unova for the Anomaly Mewtwo, and are you sure you're looking in Slumbering Weald *Shrine*, not just Slumbering Weald?

**Comment by DreamNya** [comment]
This problem will occur if you play in the Dev version, which is related to the version iteration code. The Dev version should not be used for playing, but for testing.

Before understanding the cause of this problem, you need to first understand how the Pokeclicker code works.
1. Whether the NPC appears depends on 2 conditions, whether the prerequisite steps of the task are completed and whether the NPC is completed.
2. NPC completion status is stored in the savedata, in regional order rather than code addition order, and is stored in a keyless array
3. If a PR adds a new NPC, it will cause the NPC storage index to be updated.
4. The update function is only called when the version number changes (the Dev version will not update the version number, which means the Dev version may miss the storage index update)

The storage method of gym and dungeon completion status is similar to that of temporary NPCs. I think this method is very unscientific and may be to reduce the savedata size, but the cost is that it has serious flaws and will cause many problems, such as the current problem.

Assume that there were originally 8 regions and each region had 25 temporary NPCs and all were completed. Now there is a PR that adds a new Kanto mission with 5 new Kanto NPCs. Then the range of Kanto NPCs index will become 1-30, while the range after Kanto's will become 31-205.
But since you have been playing the Dev version, you may have missed the NPC index update function (because the new PR may be merged after you upgraded the savedata to 0.10.16). There are still 1-200 NPCs in your savedata, and the range of Kanto NPC index is still 1-25. Then when loading the 26th NPC, the old Johto NPC will be mistaken for the new Kanto NPC. So this misleads the code to think that you have completed the NPC and hide it, resulting in the error.

**Comment by ver1nty** [comment]
Oh I understand. Thank you for the detailed explanation! I will close this issue now.
