### ISSUE TITLE
[SUGGESTION]: New challenge mode: Professor Oak Challenge (POC)

### ISSUE THREAD

**Issue by realkrisdino** [pokeclicker/pokeclicker#4834]
### Current Behavior

Currently there is no challenge that is a POC or similar to one. 

### Improved Behavior

In the new challenges when you start a Pokéclicker game there should be a POC challenge mode.

### Reason for change

I think it would be a unique challenge that hardcore Pokéclicker players would enjoy.

### Detailed Description

A POC is a challenge where you need to catch every available Pokémon in an area before getting the next gym badge. Like before beating Brock you need to get every possible unique Pokémon (e.g. Every Pokémon between Pallet town and Viridian Gym including the mystery egg Pokémon and mew.

**Comment by Someonealive-QN** [comment]
1. A POC is something that would be really hard to program especially because the game would whether need to look for every pokémon and search for it in the locations before the gym, plus the game would need to add a pokerom requirement for each pokémon in every gym which would be even harder.
2. This would create another case of AC players not being able to fully run an AC run because they wouldn't be able to turn it on, kind of like how Real Evo works. Which would make most of them reset and maybe quit.
3. You can already do that challenge withouth the need of this. One of the people that i do remember from my head which is making one rn is Jemleponay, which is making a POC and they are currently at pre alola/pre malva.

**Comment by Qwertypop04** [comment]
Closing for the reasons that Someonealive-QN gave
