### ISSUE TITLE
A tool to help new players

### ISSUE THREAD

**Issue by anapple96** [pokeclicker/pokeclicker#579]
(follow-up of issue #460 )
The game has a ton of Pokemon to collect, and some new player may not even know how to collect them!
So, i propose an idea of adding a hint system to the Pokedex, for a small fee.
For example, I don't have Mewtwo and I don't know where does it spawn. I can click in the Mewtwo section of the Pokedex and it will give me a hint, along the line of "This is a cave in the city that has Misty's gym.Be careful,that cave is dangerous, you'll need a good team!<"a good team" here means beating the elite four>".The hint shouldn't be too vague/accurate.
This can also applies to shop eggs and fossils
At first, i think the fee should be 500 PokeDollar

**Comment by Aegyo** [comment]
I've given some thought to this issue, but came up with something different.


Similar to how we indicate that all pokemon in a route or dungeon have been caught, we could also add pokeball indicators to eggs, evolution stones, and any other things required to find pokemon

I've noticed that even with the indicators in routes and dungeons, sometimes people don't notice (or perhaps even check) that a location has not been exhausted if new pokemon, likely because it is tedious to go around the entire map checking for pokeballs. A nice solution to this would be some kind of LocationDex where you can check all sources of pokemon at the same time.


Your idea could work too, and there is no reason we can't do both anyway. The main things we need to consider for your suggestion is how well we could generate location hints (so that we dont need to maintain a huge list of hints), and what to do for pokemon obtainable from multiple places.

**Comment by anapple96** [comment]
I think for Pokemon with multiple spawn, just create multiple hints and do a Math.floor(Math.random() * x); where x is the amount of route with that Pokemon +1
And, for hints, a system along the line of : "Spawn between" x "route and" y "route" and "Spawn in the dungeon nearest to" x "city" can work, as you can swap x and y for route number

**Comment by RedSparr0w** [comment]
Could just make it show hints where the Pokemon has a hint implemented.
Otherwise just pull it from the data and straight up tell them where it is.
```js
getPokemonHint(pokemon){
 return pokemon.hint ?? getPokemonLocation(pokemon);
}

getPokemonLocation(pokemon){
  const list = [
    ...getPokemonRoutes(pokemon),
    ...getPokemonDungeons(pokemon),
    ...getPokemonShops(pokemon),
    ...getPokemonEggs(pokemon),
    ...getPokemonRoaming(pokemon),
    ...getPokemonSafariZone(pokemon),
    ...getPokemonUnderground(pokemon),
  ];
  // return random list item.
}
```

**Comment by anapple96** [comment]
We have the wiki/bot now
