### ISSUE TITLE
[Suggestion] Masterball obtain method

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#665]
I think the Masterballs should be removed from the shop and acquired by some different method.

Some suggestions are:
- Prestige reward
- Daily quest (only allow 1 per day, harder quests)
- Underground
- First time beating the elite 4 in each region

**Comment by danfroese** [comment]
I like all of these options. Once per run could be okay, so long as you don't _have to_ catch Raikoh/Entei/Suicune every run, or if they become less of a nuisance. Otherwise, methods of acquiring more through quests or the underground would be nice. They should be more limited than they are, though.
