### ISSUE TITLE
Window Size Change Graphical Glitch[BUG] 

### ISSUE THREAD

**Issue by RandomPlayer64** [pokeclicker/pokeclicker#899]
**Info**
 - OS: Mac OS (Most Recent Version)
 - Browser Chrome
 -Unsure what version of Chrome it is, most likely the most recent
**Description:**
When in the safari zone, I changed the size of the window to make it smaller, and it messed up the entire safari zone's graphics

**Steps to Reproduce:**

1. Go to Safari Zone
2. Reduce window size so that the browser tab is a little less than half the size of the screen
3. See error

**Expected Behavior:**
I expected it to look the same and scale don in size, or move in a way where it would fit

**Screenshots:**

![Screen Shot 2020-10-07 at 5 34 40 PM](https://user-images.githubusercontent.com/72527378/95390519-80f33700-08c3-11eb-8e3c-80ca37c4059f.png)

**Comment by SpenserJ** [comment]
It looks like the game sizes (number of tiles) the safari based on the dimensions of the screen when the safari is opened for the first time since the game loaded (last refresh). You can test this by refreshing the page, setting it to whatever size you want, and then opening the Safari.

Mobile:
![image](https://user-images.githubusercontent.com/90011/96179892-d1374e00-0eee-11eb-80c5-3e0af0013a4b.png)

Desktop:
![image](https://user-images.githubusercontent.com/90011/96179979-fd52cf00-0eee-11eb-97d3-3ee0cb86f540.png)

I played around with trying to scale it dynamically, however it doesn't work well, and would reduce the playability if we used a fixed number of rows/columns. I'm going to close it since it is only a bug if you resize the window _after_ starting a safari (since last refresh), and the alternative (scaling) would have a much larger negative impact
