### ISSUE TITLE
[BUG] Item pokeball icon

### ISSUE THREAD

**Issue by antocs** [pokeclicker/pokeclicker#954]
**Info**
 - OS: Win 10
 - Browser Chrome
 - Version 0.5.7

**Description:**
When using "Soothe Bell" on Eevee to evolve, and you only one of the 2 evos cause of the time (Umbreon or Espeon), the item menu adds the pokeball icon beside him, notifying that you already got all the evos for Eevee with that item, when it's not right.

**Steps to Reproduce:**
1. Buy "Soothe Bell"
2. Use it on Eevee (you get either Espeon or Umbreon)
3. See the result (pokeball icon but you still need the other evo).

**Expected Behavior:**
Keep the non-icon if you still miss the other evo with the same item.

**Screenshots:**

**Additional Information:**

![image](https://user-images.githubusercontent.com/22413659/96320857-db06a180-1013-11eb-89b2-68cb4c5007d9.png)
![image](https://user-images.githubusercontent.com/22413659/96320861-dd68fb80-1013-11eb-81e6-fbb1630febd6.png)

**Comment by Aegyo** [comment]
This is intended, since if you use a soothe bell right then, you can only get Umbreon.
The pokeball should disappear when the time changes to something when Espeon is possible to get.

If we didn't show the pokeball here, people would think they can get the other pokemon if they keep trying to use the soothe bell.
